// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sciobjsdb/api/storage/services/v1/dataset_service_models.proto

package com.github.ScienceObjectsDB.java_api.sciobjsdb.api.storage.services.v1;

public interface UpdateDatasetFieldRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sciobjsdb.api.storage.services.v1.UpdateDatasetFieldRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.sciobjsdb.api.storage.models.v1.UpdateFieldsRequest update_request = 1 [json_name = "updateRequest"];</code>
   * @return Whether the updateRequest field is set.
   */
  boolean hasUpdateRequest();
  /**
   * <code>.sciobjsdb.api.storage.models.v1.UpdateFieldsRequest update_request = 1 [json_name = "updateRequest"];</code>
   * @return The updateRequest.
   */
  com.github.ScienceObjectsDB.java_api.sciobjsdb.api.storage.models.v1.UpdateFieldsRequest getUpdateRequest();
  /**
   * <code>.sciobjsdb.api.storage.models.v1.UpdateFieldsRequest update_request = 1 [json_name = "updateRequest"];</code>
   */
  com.github.ScienceObjectsDB.java_api.sciobjsdb.api.storage.models.v1.UpdateFieldsRequestOrBuilder getUpdateRequestOrBuilder();
}
