// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/services/ObjectLoadModels.proto

package com.github.ScienceObjectsDB.java_api.services;

/**
 * Protobuf type {@code services.CreateLinkResponse}
 */
public  final class CreateLinkResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:services.CreateLinkResponse)
    CreateLinkResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateLinkResponse.newBuilder() to construct.
  private CreateLinkResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateLinkResponse() {
    uploadLink_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateLinkResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateLinkResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            uploadLink_ = s;
            break;
          }
          case 18: {
            com.github.ScienceObjectsDB.java_api.models.Object.Builder subBuilder = null;
            if (object_ != null) {
              subBuilder = object_.toBuilder();
            }
            object_ = input.readMessage(com.github.ScienceObjectsDB.java_api.models.Object.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(object_);
              object_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.ScienceObjectsDB.java_api.services.ObjectLoadServiceModels.internal_static_services_CreateLinkResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.ScienceObjectsDB.java_api.services.ObjectLoadServiceModels.internal_static_services_CreateLinkResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse.class, com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse.Builder.class);
  }

  public static final int UPLOAD_LINK_FIELD_NUMBER = 1;
  private volatile java.lang.Object uploadLink_;
  /**
   * <code>string upload_link = 1;</code>
   * @return The uploadLink.
   */
  public java.lang.String getUploadLink() {
    java.lang.Object ref = uploadLink_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uploadLink_ = s;
      return s;
    }
  }
  /**
   * <code>string upload_link = 1;</code>
   * @return The bytes for uploadLink.
   */
  public com.google.protobuf.ByteString
      getUploadLinkBytes() {
    java.lang.Object ref = uploadLink_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uploadLink_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OBJECT_FIELD_NUMBER = 2;
  private com.github.ScienceObjectsDB.java_api.models.Object object_;
  /**
   * <code>.models.Object object = 2;</code>
   * @return Whether the object field is set.
   */
  public boolean hasObject() {
    return object_ != null;
  }
  /**
   * <code>.models.Object object = 2;</code>
   * @return The object.
   */
  public com.github.ScienceObjectsDB.java_api.models.Object getObject() {
    return object_ == null ? com.github.ScienceObjectsDB.java_api.models.Object.getDefaultInstance() : object_;
  }
  /**
   * <code>.models.Object object = 2;</code>
   */
  public com.github.ScienceObjectsDB.java_api.models.ObjectOrBuilder getObjectOrBuilder() {
    return getObject();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUploadLinkBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uploadLink_);
    }
    if (object_ != null) {
      output.writeMessage(2, getObject());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUploadLinkBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uploadLink_);
    }
    if (object_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getObject());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse)) {
      return super.equals(obj);
    }
    com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse other = (com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse) obj;

    if (!getUploadLink()
        .equals(other.getUploadLink())) return false;
    if (hasObject() != other.hasObject()) return false;
    if (hasObject()) {
      if (!getObject()
          .equals(other.getObject())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UPLOAD_LINK_FIELD_NUMBER;
    hash = (53 * hash) + getUploadLink().hashCode();
    if (hasObject()) {
      hash = (37 * hash) + OBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getObject().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code services.CreateLinkResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:services.CreateLinkResponse)
      com.github.ScienceObjectsDB.java_api.services.CreateLinkResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.ScienceObjectsDB.java_api.services.ObjectLoadServiceModels.internal_static_services_CreateLinkResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.ScienceObjectsDB.java_api.services.ObjectLoadServiceModels.internal_static_services_CreateLinkResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse.class, com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse.Builder.class);
    }

    // Construct using com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      uploadLink_ = "";

      if (objectBuilder_ == null) {
        object_ = null;
      } else {
        object_ = null;
        objectBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.ScienceObjectsDB.java_api.services.ObjectLoadServiceModels.internal_static_services_CreateLinkResponse_descriptor;
    }

    @java.lang.Override
    public com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse getDefaultInstanceForType() {
      return com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse build() {
      com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse buildPartial() {
      com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse result = new com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse(this);
      result.uploadLink_ = uploadLink_;
      if (objectBuilder_ == null) {
        result.object_ = object_;
      } else {
        result.object_ = objectBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse) {
        return mergeFrom((com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse other) {
      if (other == com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse.getDefaultInstance()) return this;
      if (!other.getUploadLink().isEmpty()) {
        uploadLink_ = other.uploadLink_;
        onChanged();
      }
      if (other.hasObject()) {
        mergeObject(other.getObject());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object uploadLink_ = "";
    /**
     * <code>string upload_link = 1;</code>
     * @return The uploadLink.
     */
    public java.lang.String getUploadLink() {
      java.lang.Object ref = uploadLink_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uploadLink_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string upload_link = 1;</code>
     * @return The bytes for uploadLink.
     */
    public com.google.protobuf.ByteString
        getUploadLinkBytes() {
      java.lang.Object ref = uploadLink_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uploadLink_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string upload_link = 1;</code>
     * @param value The uploadLink to set.
     * @return This builder for chaining.
     */
    public Builder setUploadLink(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uploadLink_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string upload_link = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUploadLink() {
      
      uploadLink_ = getDefaultInstance().getUploadLink();
      onChanged();
      return this;
    }
    /**
     * <code>string upload_link = 1;</code>
     * @param value The bytes for uploadLink to set.
     * @return This builder for chaining.
     */
    public Builder setUploadLinkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uploadLink_ = value;
      onChanged();
      return this;
    }

    private com.github.ScienceObjectsDB.java_api.models.Object object_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ScienceObjectsDB.java_api.models.Object, com.github.ScienceObjectsDB.java_api.models.Object.Builder, com.github.ScienceObjectsDB.java_api.models.ObjectOrBuilder> objectBuilder_;
    /**
     * <code>.models.Object object = 2;</code>
     * @return Whether the object field is set.
     */
    public boolean hasObject() {
      return objectBuilder_ != null || object_ != null;
    }
    /**
     * <code>.models.Object object = 2;</code>
     * @return The object.
     */
    public com.github.ScienceObjectsDB.java_api.models.Object getObject() {
      if (objectBuilder_ == null) {
        return object_ == null ? com.github.ScienceObjectsDB.java_api.models.Object.getDefaultInstance() : object_;
      } else {
        return objectBuilder_.getMessage();
      }
    }
    /**
     * <code>.models.Object object = 2;</code>
     */
    public Builder setObject(com.github.ScienceObjectsDB.java_api.models.Object value) {
      if (objectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        object_ = value;
        onChanged();
      } else {
        objectBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.models.Object object = 2;</code>
     */
    public Builder setObject(
        com.github.ScienceObjectsDB.java_api.models.Object.Builder builderForValue) {
      if (objectBuilder_ == null) {
        object_ = builderForValue.build();
        onChanged();
      } else {
        objectBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.models.Object object = 2;</code>
     */
    public Builder mergeObject(com.github.ScienceObjectsDB.java_api.models.Object value) {
      if (objectBuilder_ == null) {
        if (object_ != null) {
          object_ =
            com.github.ScienceObjectsDB.java_api.models.Object.newBuilder(object_).mergeFrom(value).buildPartial();
        } else {
          object_ = value;
        }
        onChanged();
      } else {
        objectBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.models.Object object = 2;</code>
     */
    public Builder clearObject() {
      if (objectBuilder_ == null) {
        object_ = null;
        onChanged();
      } else {
        object_ = null;
        objectBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.models.Object object = 2;</code>
     */
    public com.github.ScienceObjectsDB.java_api.models.Object.Builder getObjectBuilder() {
      
      onChanged();
      return getObjectFieldBuilder().getBuilder();
    }
    /**
     * <code>.models.Object object = 2;</code>
     */
    public com.github.ScienceObjectsDB.java_api.models.ObjectOrBuilder getObjectOrBuilder() {
      if (objectBuilder_ != null) {
        return objectBuilder_.getMessageOrBuilder();
      } else {
        return object_ == null ?
            com.github.ScienceObjectsDB.java_api.models.Object.getDefaultInstance() : object_;
      }
    }
    /**
     * <code>.models.Object object = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ScienceObjectsDB.java_api.models.Object, com.github.ScienceObjectsDB.java_api.models.Object.Builder, com.github.ScienceObjectsDB.java_api.models.ObjectOrBuilder> 
        getObjectFieldBuilder() {
      if (objectBuilder_ == null) {
        objectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.ScienceObjectsDB.java_api.models.Object, com.github.ScienceObjectsDB.java_api.models.Object.Builder, com.github.ScienceObjectsDB.java_api.models.ObjectOrBuilder>(
                getObject(),
                getParentForChildren(),
                isClean());
        object_ = null;
      }
      return objectBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:services.CreateLinkResponse)
  }

  // @@protoc_insertion_point(class_scope:services.CreateLinkResponse)
  private static final com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse();
  }

  public static com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateLinkResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateLinkResponse>() {
    @java.lang.Override
    public CreateLinkResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateLinkResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateLinkResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateLinkResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.ScienceObjectsDB.java_api.services.CreateLinkResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

