// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aruna/api/storage/services/v2/info_service.proto

// Protobuf Java Version: 3.25.3
package com.aruna.api.storage.services.v2;

public interface GetAnnouncementResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aruna.api.storage.services.v2.GetAnnouncementResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.aruna.api.storage.services.v2.Announcement announcement = 1 [json_name = "announcement"];</code>
   * @return Whether the announcement field is set.
   */
  boolean hasAnnouncement();
  /**
   * <code>.aruna.api.storage.services.v2.Announcement announcement = 1 [json_name = "announcement"];</code>
   * @return The announcement.
   */
  com.aruna.api.storage.services.v2.Announcement getAnnouncement();
  /**
   * <code>.aruna.api.storage.services.v2.Announcement announcement = 1 [json_name = "announcement"];</code>
   */
  com.aruna.api.storage.services.v2.AnnouncementOrBuilder getAnnouncementOrBuilder();
}
