// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aruna/api/storage/services/v2/object_service.proto

// Protobuf Java Version: 3.25.3
package com.aruna.api.storage.services.v2;

public final class ObjectServiceProto {
  private ObjectServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_CreateObjectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_CreateObjectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_CreateObjectResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_CreateObjectResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_GetUploadURLRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_GetUploadURLRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_GetUploadURLResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_GetUploadURLResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_GetDownloadURLRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_GetDownloadURLRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_GetDownloadURLResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_GetDownloadURLResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_CompletedPart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_CompletedPart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_FinishObjectStagingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_FinishObjectStagingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_FinishObjectStagingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_FinishObjectStagingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_UpdateObjectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_UpdateObjectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_UpdateObjectResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_UpdateObjectResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_CloneObjectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_CloneObjectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_CloneObjectResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_CloneObjectResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_DeleteObjectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_DeleteObjectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_DeleteObjectResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_DeleteObjectResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_GetObjectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_GetObjectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_GetObjectResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_GetObjectResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_GetObjectsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_GetObjectsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_GetObjectsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_GetObjectsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_GetObjectRevisionsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_GetObjectRevisionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_GetObjectRevisionsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_GetObjectRevisionsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_GetLatestObjectRevisionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_GetLatestObjectRevisionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_GetLatestObjectRevisionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_GetLatestObjectRevisionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_GetObjectEndpointsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_GetObjectEndpointsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_UpdateObjectTitleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_UpdateObjectTitleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_UpdateObjectTitleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_UpdateObjectTitleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_UpdateObjectAuthorsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_UpdateObjectAuthorsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_UpdateObjectAuthorsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_UpdateObjectAuthorsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_SetObjectHashesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_SetObjectHashesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aruna_api_storage_services_v2_SetObjectHashesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aruna_api_storage_services_v2_SetObjectHashesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2aruna/api/storage/services/v2/object_s" +
      "ervice.proto\022\035aruna.api.storage.services" +
      ".v2\032(aruna/api/storage/models/v2/models." +
      "proto\032\034google/api/annotations.proto\032\033goo" +
      "gle/api/visibility.proto\"\374\004\n\023CreateObjec" +
      "tRequest\022\022\n\004name\030\001 \001(\tR\004name\022\024\n\005title\030\014 " +
      "\001(\tR\005title\022 \n\013description\030\002 \001(\tR\013descrip" +
      "tion\022D\n\nkey_values\030\003 \003(\0132%.aruna.api.sto" +
      "rage.models.v2.KeyValueR\tkeyValues\022C\n\tre" +
      "lations\030\004 \003(\0132%.aruna.api.storage.models" +
      ".v2.RelationR\trelations\022E\n\ndata_class\030\005 " +
      "\001(\0162&.aruna.api.storage.models.v2.DataCl" +
      "assR\tdataClass\022\037\n\nproject_id\030\006 \001(\tH\000R\tpr" +
      "ojectId\022%\n\rcollection_id\030\007 \001(\tH\000R\014collec" +
      "tionId\022\037\n\ndataset_id\030\010 \001(\tH\000R\tdatasetId\022" +
      "9\n\006hashes\030\t \003(\0132!.aruna.api.storage.mode" +
      "ls.v2.HashR\006hashes\0220\n\024metadata_license_t" +
      "ag\030\n \001(\tR\022metadataLicenseTag\022(\n\020data_lic" +
      "ense_tag\030\013 \001(\tR\016dataLicenseTag\022=\n\007author" +
      "s\030\r \003(\0132#.aruna.api.storage.models.v2.Au" +
      "thorR\007authorsB\010\n\006parent\"S\n\024CreateObjectR" +
      "esponse\022;\n\006object\030\001 \001(\0132#.aruna.api.stor" +
      "age.models.v2.ObjectR\006object\"q\n\023GetUploa" +
      "dURLRequest\022\033\n\tobject_id\030\001 \001(\tR\010objectId" +
      "\022\034\n\tmultipart\030\002 \001(\010R\tmultipart\022\037\n\013part_n" +
      "umber\030\003 \001(\005R\npartNumber\"(\n\024GetUploadURLR" +
      "esponse\022\020\n\003url\030\001 \001(\tR\003url\"4\n\025GetDownload" +
      "URLRequest\022\033\n\tobject_id\030\001 \001(\tR\010objectId\"" +
      "*\n\026GetDownloadURLResponse\022\020\n\003url\030\001 \001(\tR\003" +
      "url\"7\n\rCompletedPart\022\022\n\004etag\030\001 \001(\tR\004etag" +
      "\022\022\n\004part\030\002 \001(\003R\004part\"\354\001\n\032FinishObjectSta" +
      "gingRequest\022\033\n\tobject_id\030\001 \001(\tR\010objectId" +
      "\022\037\n\013content_len\030\002 \001(\003R\ncontentLen\0229\n\006has" +
      "hes\030\003 \003(\0132!.aruna.api.storage.models.v2." +
      "HashR\006hashes\022U\n\017completed_parts\030\004 \003(\0132,." +
      "aruna.api.storage.services.v2.CompletedP" +
      "artR\016completedParts\"Z\n\033FinishObjectStagi" +
      "ngResponse\022;\n\006object\030\001 \001(\0132#.aruna.api.s" +
      "torage.models.v2.ObjectR\006object\"\333\005\n\023Upda" +
      "teObjectRequest\022\033\n\tobject_id\030\001 \001(\tR\010obje" +
      "ctId\022\027\n\004name\030\002 \001(\tH\001R\004name\210\001\001\022%\n\013descrip" +
      "tion\030\003 \001(\tH\002R\013description\210\001\001\022K\n\016add_key_" +
      "values\030\004 \003(\0132%.aruna.api.storage.models." +
      "v2.KeyValueR\014addKeyValues\022Q\n\021remove_key_" +
      "values\030\005 \003(\0132%.aruna.api.storage.models." +
      "v2.KeyValueR\017removeKeyValues\022E\n\ndata_cla" +
      "ss\030\007 \001(\0162&.aruna.api.storage.models.v2.D" +
      "ataClassR\tdataClass\022\037\n\nproject_id\030\010 \001(\tH" +
      "\000R\tprojectId\022%\n\rcollection_id\030\t \001(\tH\000R\014c" +
      "ollectionId\022\037\n\ndataset_id\030\n \001(\tH\000R\tdatas" +
      "etId\0229\n\006hashes\030\014 \003(\0132!.aruna.api.storage" +
      ".models.v2.HashR\006hashes\022%\n\016force_revisio" +
      "n\030\r \001(\010R\rforceRevision\0225\n\024metadata_licen" +
      "se_tag\030\016 \001(\tH\003R\022metadataLicenseTag\210\001\001\022-\n" +
      "\020data_license_tag\030\017 \001(\tH\004R\016dataLicenseTa" +
      "g\210\001\001B\010\n\006parentB\007\n\005_nameB\016\n\014_descriptionB" +
      "\027\n\025_metadata_license_tagB\023\n\021_data_licens" +
      "e_tag\"v\n\024UpdateObjectResponse\022;\n\006object\030" +
      "\001 \001(\0132#.aruna.api.storage.models.v2.Obje" +
      "ctR\006object\022!\n\014new_revision\030\002 \001(\010R\013newRev" +
      "ision\"\244\001\n\022CloneObjectRequest\022\033\n\tobject_i" +
      "d\030\001 \001(\tR\010objectId\022\037\n\nproject_id\030\002 \001(\tH\000R" +
      "\tprojectId\022%\n\rcollection_id\030\003 \001(\tH\000R\014col" +
      "lectionId\022\037\n\ndataset_id\030\004 \001(\tH\000R\tdataset" +
      "IdB\010\n\006parent\"R\n\023CloneObjectResponse\022;\n\006o" +
      "bject\030\001 \001(\0132#.aruna.api.storage.models.v" +
      "2.ObjectR\006object\"Y\n\023DeleteObjectRequest\022" +
      "\033\n\tobject_id\030\001 \001(\tR\010objectId\022%\n\016with_rev" +
      "isions\030\002 \001(\010R\rwithRevisions\"\026\n\024DeleteObj" +
      "ectResponse\"/\n\020GetObjectRequest\022\033\n\tobjec" +
      "t_id\030\001 \001(\tR\010objectId\"P\n\021GetObjectRespons" +
      "e\022;\n\006object\030\001 \001(\0132#.aruna.api.storage.mo" +
      "dels.v2.ObjectR\006object\"2\n\021GetObjectsRequ" +
      "est\022\035\n\nobject_ids\030\001 \003(\tR\tobjectIds\"S\n\022Ge" +
      "tObjectsResponse\022=\n\007objects\030\001 \003(\0132#.arun" +
      "a.api.storage.models.v2.ObjectR\007objects\"" +
      "8\n\031GetObjectRevisionsRequest\022\033\n\tobject_i" +
      "d\030\002 \001(\tR\010objectId\"[\n\032GetObjectRevisionsR" +
      "esponse\022=\n\007objects\030\001 \003(\0132#.aruna.api.sto" +
      "rage.models.v2.ObjectR\007objects\"=\n\036GetLat" +
      "estObjectRevisionRequest\022\033\n\tobject_id\030\001 " +
      "\001(\tR\010objectId\"^\n\037GetLatestObjectRevision" +
      "Response\022;\n\006object\030\001 \001(\0132#.aruna.api.sto" +
      "rage.models.v2.ObjectR\006object\"]\n\031GetObje" +
      "ctEndpointsRequest\022#\n\rcollection_id\030\001 \001(" +
      "\tR\014collectionId\022\033\n\tobject_id\030\002 \001(\tR\010obje" +
      "ctId\"M\n\030UpdateObjectTitleRequest\022\033\n\tobje" +
      "ct_id\030\001 \001(\tR\010objectId\022\024\n\005title\030\002 \001(\tR\005ti" +
      "tle\"X\n\031UpdateObjectTitleResponse\022;\n\006obje" +
      "ct\030\001 \001(\0132#.aruna.api.storage.models.v2.O" +
      "bjectR\006object\"\313\001\n\032UpdateObjectAuthorsReq" +
      "uest\022\033\n\tobject_id\030\001 \001(\tR\010objectId\022D\n\013add" +
      "_authors\030\002 \003(\0132#.aruna.api.storage.model" +
      "s.v2.AuthorR\naddAuthors\022J\n\016remove_author" +
      "s\030\003 \003(\0132#.aruna.api.storage.models.v2.Au" +
      "thorR\rremoveAuthors\"Z\n\033UpdateObjectAutho" +
      "rsResponse\022;\n\006object\030\001 \001(\0132#.aruna.api.s" +
      "torage.models.v2.ObjectR\006object\"p\n\026SetOb" +
      "jectHashesRequest\022\033\n\tobject_id\030\001 \001(\tR\010ob" +
      "jectId\0229\n\006hashes\030\002 \003(\0132!.aruna.api.stora" +
      "ge.models.v2.HashR\006hashes\"V\n\027SetObjectHa" +
      "shesResponse\022;\n\006object\030\001 \001(\0132#.aruna.api" +
      ".storage.models.v2.ObjectR\006object2\303\017\n\rOb" +
      "jectService\022\217\001\n\014CreateObject\0222.aruna.api" +
      ".storage.services.v2.CreateObjectRequest" +
      "\0323.aruna.api.storage.services.v2.CreateO" +
      "bjectResponse\"\026\202\323\344\223\002\020\"\013/v2/objects:\001*\022\237\001" +
      "\n\014GetUploadURL\0222.aruna.api.storage.servi" +
      "ces.v2.GetUploadURLRequest\0323.aruna.api.s" +
      "torage.services.v2.GetUploadURLResponse\"" +
      "&\202\323\344\223\002 \022\036/v2/objects/{object_id}/upload\022" +
      "\247\001\n\016GetDownloadURL\0224.aruna.api.storage.s" +
      "ervices.v2.GetDownloadURLRequest\0325.aruna" +
      ".api.storage.services.v2.GetDownloadURLR" +
      "esponse\"(\202\323\344\223\002\"\022 /v2/objects/{object_id}" +
      "/download\022\267\001\n\023FinishObjectStaging\0229.arun" +
      "a.api.storage.services.v2.FinishObjectSt" +
      "agingRequest\032:.aruna.api.storage.service" +
      "s.v2.FinishObjectStagingResponse\")\202\323\344\223\002#" +
      "2\036/v2/objects/{object_id}/finish:\001*\022\233\001\n\014" +
      "UpdateObject\0222.aruna.api.storage.service" +
      "s.v2.UpdateObjectRequest\0323.aruna.api.sto" +
      "rage.services.v2.UpdateObjectResponse\"\"\202" +
      "\323\344\223\002\034\"\027/v2/objects/{object_id}:\001*\022\226\001\n\013Cl" +
      "oneObject\0221.aruna.api.storage.services.v" +
      "2.CloneObjectRequest\0322.aruna.api.storage" +
      ".services.v2.CloneObjectResponse\" \202\323\344\223\002\032" +
      "\"\025/v2/{object_id}/clone:\001*\022\233\001\n\014DeleteObj" +
      "ect\0222.aruna.api.storage.services.v2.Dele" +
      "teObjectRequest\0323.aruna.api.storage.serv" +
      "ices.v2.DeleteObjectResponse\"\"\202\323\344\223\002\034*\027/v" +
      "2/objects/{object_id}:\001*\022\217\001\n\tGetObject\022/" +
      ".aruna.api.storage.services.v2.GetObject" +
      "Request\0320.aruna.api.storage.services.v2." +
      "GetObjectResponse\"\037\202\323\344\223\002\031\022\027/v2/objects/{" +
      "object_id}\022\206\001\n\nGetObjects\0220.aruna.api.st" +
      "orage.services.v2.GetObjectsRequest\0321.ar" +
      "una.api.storage.services.v2.GetObjectsRe" +
      "sponse\"\023\202\323\344\223\002\r\022\013/v2/objects\022\260\001\n\021UpdateOb" +
      "jectTitle\0227.aruna.api.storage.services.v" +
      "2.UpdateObjectTitleRequest\0328.aruna.api.s" +
      "torage.services.v2.UpdateObjectTitleResp" +
      "onse\"(\202\323\344\223\002\"\"\035/v2/objects/{object_id}/ti" +
      "tle:\001*\022\270\001\n\023UpdateObjectAuthors\0229.aruna.a" +
      "pi.storage.services.v2.UpdateObjectAutho" +
      "rsRequest\032:.aruna.api.storage.services.v" +
      "2.UpdateObjectAuthorsResponse\"*\202\323\344\223\002$\"\037/" +
      "v2/objects/{object_id}/authors:\001*\022\253\001\n\017Se" +
      "tObjectHashes\0225.aruna.api.storage.servic" +
      "es.v2.SetObjectHashesRequest\0326.aruna.api" +
      ".storage.services.v2.SetObjectHashesResp" +
      "onse\")\202\323\344\223\002#\"\036/v2/objects/{object_id}/ha" +
      "shes:\001*\032\016\372\322\344\223\002\010\022\006SERVERB\221\002\n!com.aruna.ap" +
      "i.storage.services.v2B\022ObjectServiceProt" +
      "oP\001Z?github.com/ArunaStorage/go-api/v2/a" +
      "runa/api/storage/services/v2\242\002\004AASS\252\002\035Ar" +
      "una.Api.Storage.Services.V2\312\002\035Aruna\\Api\\" +
      "Storage\\Services\\V2\342\002)Aruna\\Api\\Storage\\" +
      "Services\\V2\\GPBMetadata\352\002!Aruna::Api::St" +
      "orage::Services::V2b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.aruna.api.storage.models.v2.ModelsProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.VisibilityProto.getDescriptor(),
        });
    internal_static_aruna_api_storage_services_v2_CreateObjectRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_aruna_api_storage_services_v2_CreateObjectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_CreateObjectRequest_descriptor,
        new java.lang.String[] { "Name", "Title", "Description", "KeyValues", "Relations", "DataClass", "ProjectId", "CollectionId", "DatasetId", "Hashes", "MetadataLicenseTag", "DataLicenseTag", "Authors", "Parent", });
    internal_static_aruna_api_storage_services_v2_CreateObjectResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_aruna_api_storage_services_v2_CreateObjectResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_CreateObjectResponse_descriptor,
        new java.lang.String[] { "Object", });
    internal_static_aruna_api_storage_services_v2_GetUploadURLRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_aruna_api_storage_services_v2_GetUploadURLRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_GetUploadURLRequest_descriptor,
        new java.lang.String[] { "ObjectId", "Multipart", "PartNumber", });
    internal_static_aruna_api_storage_services_v2_GetUploadURLResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_aruna_api_storage_services_v2_GetUploadURLResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_GetUploadURLResponse_descriptor,
        new java.lang.String[] { "Url", });
    internal_static_aruna_api_storage_services_v2_GetDownloadURLRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_aruna_api_storage_services_v2_GetDownloadURLRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_GetDownloadURLRequest_descriptor,
        new java.lang.String[] { "ObjectId", });
    internal_static_aruna_api_storage_services_v2_GetDownloadURLResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_aruna_api_storage_services_v2_GetDownloadURLResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_GetDownloadURLResponse_descriptor,
        new java.lang.String[] { "Url", });
    internal_static_aruna_api_storage_services_v2_CompletedPart_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_aruna_api_storage_services_v2_CompletedPart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_CompletedPart_descriptor,
        new java.lang.String[] { "Etag", "Part", });
    internal_static_aruna_api_storage_services_v2_FinishObjectStagingRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_aruna_api_storage_services_v2_FinishObjectStagingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_FinishObjectStagingRequest_descriptor,
        new java.lang.String[] { "ObjectId", "ContentLen", "Hashes", "CompletedParts", });
    internal_static_aruna_api_storage_services_v2_FinishObjectStagingResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_aruna_api_storage_services_v2_FinishObjectStagingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_FinishObjectStagingResponse_descriptor,
        new java.lang.String[] { "Object", });
    internal_static_aruna_api_storage_services_v2_UpdateObjectRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_aruna_api_storage_services_v2_UpdateObjectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_UpdateObjectRequest_descriptor,
        new java.lang.String[] { "ObjectId", "Name", "Description", "AddKeyValues", "RemoveKeyValues", "DataClass", "ProjectId", "CollectionId", "DatasetId", "Hashes", "ForceRevision", "MetadataLicenseTag", "DataLicenseTag", "Parent", });
    internal_static_aruna_api_storage_services_v2_UpdateObjectResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_aruna_api_storage_services_v2_UpdateObjectResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_UpdateObjectResponse_descriptor,
        new java.lang.String[] { "Object", "NewRevision", });
    internal_static_aruna_api_storage_services_v2_CloneObjectRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_aruna_api_storage_services_v2_CloneObjectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_CloneObjectRequest_descriptor,
        new java.lang.String[] { "ObjectId", "ProjectId", "CollectionId", "DatasetId", "Parent", });
    internal_static_aruna_api_storage_services_v2_CloneObjectResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_aruna_api_storage_services_v2_CloneObjectResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_CloneObjectResponse_descriptor,
        new java.lang.String[] { "Object", });
    internal_static_aruna_api_storage_services_v2_DeleteObjectRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_aruna_api_storage_services_v2_DeleteObjectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_DeleteObjectRequest_descriptor,
        new java.lang.String[] { "ObjectId", "WithRevisions", });
    internal_static_aruna_api_storage_services_v2_DeleteObjectResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_aruna_api_storage_services_v2_DeleteObjectResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_DeleteObjectResponse_descriptor,
        new java.lang.String[] { });
    internal_static_aruna_api_storage_services_v2_GetObjectRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_aruna_api_storage_services_v2_GetObjectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_GetObjectRequest_descriptor,
        new java.lang.String[] { "ObjectId", });
    internal_static_aruna_api_storage_services_v2_GetObjectResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_aruna_api_storage_services_v2_GetObjectResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_GetObjectResponse_descriptor,
        new java.lang.String[] { "Object", });
    internal_static_aruna_api_storage_services_v2_GetObjectsRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_aruna_api_storage_services_v2_GetObjectsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_GetObjectsRequest_descriptor,
        new java.lang.String[] { "ObjectIds", });
    internal_static_aruna_api_storage_services_v2_GetObjectsResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_aruna_api_storage_services_v2_GetObjectsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_GetObjectsResponse_descriptor,
        new java.lang.String[] { "Objects", });
    internal_static_aruna_api_storage_services_v2_GetObjectRevisionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_aruna_api_storage_services_v2_GetObjectRevisionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_GetObjectRevisionsRequest_descriptor,
        new java.lang.String[] { "ObjectId", });
    internal_static_aruna_api_storage_services_v2_GetObjectRevisionsResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_aruna_api_storage_services_v2_GetObjectRevisionsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_GetObjectRevisionsResponse_descriptor,
        new java.lang.String[] { "Objects", });
    internal_static_aruna_api_storage_services_v2_GetLatestObjectRevisionRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_aruna_api_storage_services_v2_GetLatestObjectRevisionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_GetLatestObjectRevisionRequest_descriptor,
        new java.lang.String[] { "ObjectId", });
    internal_static_aruna_api_storage_services_v2_GetLatestObjectRevisionResponse_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_aruna_api_storage_services_v2_GetLatestObjectRevisionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_GetLatestObjectRevisionResponse_descriptor,
        new java.lang.String[] { "Object", });
    internal_static_aruna_api_storage_services_v2_GetObjectEndpointsRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_aruna_api_storage_services_v2_GetObjectEndpointsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_GetObjectEndpointsRequest_descriptor,
        new java.lang.String[] { "CollectionId", "ObjectId", });
    internal_static_aruna_api_storage_services_v2_UpdateObjectTitleRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_aruna_api_storage_services_v2_UpdateObjectTitleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_UpdateObjectTitleRequest_descriptor,
        new java.lang.String[] { "ObjectId", "Title", });
    internal_static_aruna_api_storage_services_v2_UpdateObjectTitleResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_aruna_api_storage_services_v2_UpdateObjectTitleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_UpdateObjectTitleResponse_descriptor,
        new java.lang.String[] { "Object", });
    internal_static_aruna_api_storage_services_v2_UpdateObjectAuthorsRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_aruna_api_storage_services_v2_UpdateObjectAuthorsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_UpdateObjectAuthorsRequest_descriptor,
        new java.lang.String[] { "ObjectId", "AddAuthors", "RemoveAuthors", });
    internal_static_aruna_api_storage_services_v2_UpdateObjectAuthorsResponse_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_aruna_api_storage_services_v2_UpdateObjectAuthorsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_UpdateObjectAuthorsResponse_descriptor,
        new java.lang.String[] { "Object", });
    internal_static_aruna_api_storage_services_v2_SetObjectHashesRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_aruna_api_storage_services_v2_SetObjectHashesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_SetObjectHashesRequest_descriptor,
        new java.lang.String[] { "ObjectId", "Hashes", });
    internal_static_aruna_api_storage_services_v2_SetObjectHashesResponse_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_aruna_api_storage_services_v2_SetObjectHashesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aruna_api_storage_services_v2_SetObjectHashesResponse_descriptor,
        new java.lang.String[] { "Object", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.VisibilityProto.apiVisibility);
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.aruna.api.storage.models.v2.ModelsProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.VisibilityProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
