// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/services/v1/object_load_models.proto

package com.github.ScienceObjectsDB.java_api.api.services.v1;

public interface CreateDownloadLinkStreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.services.v1.CreateDownloadLinkStreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.services.v1.CreateDownloadLinkStreamRequest.DatasetQuery dataset = 1 [json_name = "dataset"];</code>
   * @return Whether the dataset field is set.
   */
  boolean hasDataset();
  /**
   * <code>.api.services.v1.CreateDownloadLinkStreamRequest.DatasetQuery dataset = 1 [json_name = "dataset"];</code>
   * @return The dataset.
   */
  com.github.ScienceObjectsDB.java_api.api.services.v1.CreateDownloadLinkStreamRequest.DatasetQuery getDataset();
  /**
   * <code>.api.services.v1.CreateDownloadLinkStreamRequest.DatasetQuery dataset = 1 [json_name = "dataset"];</code>
   */
  com.github.ScienceObjectsDB.java_api.api.services.v1.CreateDownloadLinkStreamRequest.DatasetQueryOrBuilder getDatasetOrBuilder();

  /**
   * <code>.api.services.v1.CreateDownloadLinkStreamRequest.DatasetVersionQuery dataset_version = 3 [json_name = "datasetVersion"];</code>
   * @return Whether the datasetVersion field is set.
   */
  boolean hasDatasetVersion();
  /**
   * <code>.api.services.v1.CreateDownloadLinkStreamRequest.DatasetVersionQuery dataset_version = 3 [json_name = "datasetVersion"];</code>
   * @return The datasetVersion.
   */
  com.github.ScienceObjectsDB.java_api.api.services.v1.CreateDownloadLinkStreamRequest.DatasetVersionQuery getDatasetVersion();
  /**
   * <code>.api.services.v1.CreateDownloadLinkStreamRequest.DatasetVersionQuery dataset_version = 3 [json_name = "datasetVersion"];</code>
   */
  com.github.ScienceObjectsDB.java_api.api.services.v1.CreateDownloadLinkStreamRequest.DatasetVersionQueryOrBuilder getDatasetVersionOrBuilder();

  /**
   * <code>.api.services.v1.CreateDownloadLinkStreamRequest.DateRangeQuery date_range = 4 [json_name = "dateRange"];</code>
   * @return Whether the dateRange field is set.
   */
  boolean hasDateRange();
  /**
   * <code>.api.services.v1.CreateDownloadLinkStreamRequest.DateRangeQuery date_range = 4 [json_name = "dateRange"];</code>
   * @return The dateRange.
   */
  com.github.ScienceObjectsDB.java_api.api.services.v1.CreateDownloadLinkStreamRequest.DateRangeQuery getDateRange();
  /**
   * <code>.api.services.v1.CreateDownloadLinkStreamRequest.DateRangeQuery date_range = 4 [json_name = "dateRange"];</code>
   */
  com.github.ScienceObjectsDB.java_api.api.services.v1.CreateDownloadLinkStreamRequest.DateRangeQueryOrBuilder getDateRangeOrBuilder();

  public com.github.ScienceObjectsDB.java_api.api.services.v1.CreateDownloadLinkStreamRequest.QueryCase getQueryCase();
}
