// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/models/ObjectModels.proto

package com.github.ScienceObjectsDB.java_api.models;

/**
 * Protobuf type {@code models.Object}
 */
public  final class Object extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:models.Object)
    ObjectOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Object.newBuilder() to construct.
  private Object(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Object() {
    id_ = "";
    filename_ = "";
    filetype_ = "";
    labels_ = java.util.Collections.emptyList();
    metadata_ = java.util.Collections.emptyList();
    uploadId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Object();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Object(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            filename_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            filetype_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              labels_ = new java.util.ArrayList<com.github.ScienceObjectsDB.java_api.models.Label>();
              mutable_bitField0_ |= 0x00000001;
            }
            labels_.add(
                input.readMessage(com.github.ScienceObjectsDB.java_api.models.Label.parser(), extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              metadata_ = new java.util.ArrayList<com.github.ScienceObjectsDB.java_api.models.Metadata>();
              mutable_bitField0_ |= 0x00000002;
            }
            metadata_.add(
                input.readMessage(com.github.ScienceObjectsDB.java_api.models.Metadata.parser(), extensionRegistry));
            break;
          }
          case 50: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (created_ != null) {
              subBuilder = created_.toBuilder();
            }
            created_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(created_);
              created_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.github.ScienceObjectsDB.java_api.models.Location.Builder subBuilder = null;
            if (location_ != null) {
              subBuilder = location_.toBuilder();
            }
            location_ = input.readMessage(com.github.ScienceObjectsDB.java_api.models.Location.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(location_);
              location_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            com.github.ScienceObjectsDB.java_api.models.Origin.Builder subBuilder = null;
            if (origin_ != null) {
              subBuilder = origin_.toBuilder();
            }
            origin_ = input.readMessage(com.github.ScienceObjectsDB.java_api.models.Origin.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(origin_);
              origin_ = subBuilder.buildPartial();
            }

            break;
          }
          case 72: {

            contentLen_ = input.readInt64();
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            uploadId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        labels_ = java.util.Collections.unmodifiableList(labels_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        metadata_ = java.util.Collections.unmodifiableList(metadata_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.ScienceObjectsDB.java_api.models.ObjectModels.internal_static_models_Object_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.ScienceObjectsDB.java_api.models.ObjectModels.internal_static_models_Object_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.ScienceObjectsDB.java_api.models.Object.class, com.github.ScienceObjectsDB.java_api.models.Object.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   *ID of the entity
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *ID of the entity
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILENAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object filename_;
  /**
   * <pre>
   * Filename: Name of the original file e.g.: mydata.json
   * </pre>
   *
   * <code>string filename = 2;</code>
   * @return The filename.
   */
  public java.lang.String getFilename() {
    java.lang.Object ref = filename_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filename_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Filename: Name of the original file e.g.: mydata.json
   * </pre>
   *
   * <code>string filename = 2;</code>
   * @return The bytes for filename.
   */
  public com.google.protobuf.ByteString
      getFilenameBytes() {
    java.lang.Object ref = filename_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filename_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILETYPE_FIELD_NUMBER = 3;
  private volatile java.lang.Object filetype_;
  /**
   * <pre>
   * Filetype: Type of the stored file, e.g.: json, gbff,...
   * </pre>
   *
   * <code>string filetype = 3;</code>
   * @return The filetype.
   */
  public java.lang.String getFiletype() {
    java.lang.Object ref = filetype_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filetype_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Filetype: Type of the stored file, e.g.: json, gbff,...
   * </pre>
   *
   * <code>string filetype = 3;</code>
   * @return The bytes for filetype.
   */
  public com.google.protobuf.ByteString
      getFiletypeBytes() {
    java.lang.Object ref = filetype_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filetype_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LABELS_FIELD_NUMBER = 4;
  private java.util.List<com.github.ScienceObjectsDB.java_api.models.Label> labels_;
  /**
   * <code>repeated .models.Label labels = 4;</code>
   */
  public java.util.List<com.github.ScienceObjectsDB.java_api.models.Label> getLabelsList() {
    return labels_;
  }
  /**
   * <code>repeated .models.Label labels = 4;</code>
   */
  public java.util.List<? extends com.github.ScienceObjectsDB.java_api.models.LabelOrBuilder> 
      getLabelsOrBuilderList() {
    return labels_;
  }
  /**
   * <code>repeated .models.Label labels = 4;</code>
   */
  public int getLabelsCount() {
    return labels_.size();
  }
  /**
   * <code>repeated .models.Label labels = 4;</code>
   */
  public com.github.ScienceObjectsDB.java_api.models.Label getLabels(int index) {
    return labels_.get(index);
  }
  /**
   * <code>repeated .models.Label labels = 4;</code>
   */
  public com.github.ScienceObjectsDB.java_api.models.LabelOrBuilder getLabelsOrBuilder(
      int index) {
    return labels_.get(index);
  }

  public static final int METADATA_FIELD_NUMBER = 5;
  private java.util.List<com.github.ScienceObjectsDB.java_api.models.Metadata> metadata_;
  /**
   * <code>repeated .models.Metadata metadata = 5;</code>
   */
  public java.util.List<com.github.ScienceObjectsDB.java_api.models.Metadata> getMetadataList() {
    return metadata_;
  }
  /**
   * <code>repeated .models.Metadata metadata = 5;</code>
   */
  public java.util.List<? extends com.github.ScienceObjectsDB.java_api.models.MetadataOrBuilder> 
      getMetadataOrBuilderList() {
    return metadata_;
  }
  /**
   * <code>repeated .models.Metadata metadata = 5;</code>
   */
  public int getMetadataCount() {
    return metadata_.size();
  }
  /**
   * <code>repeated .models.Metadata metadata = 5;</code>
   */
  public com.github.ScienceObjectsDB.java_api.models.Metadata getMetadata(int index) {
    return metadata_.get(index);
  }
  /**
   * <code>repeated .models.Metadata metadata = 5;</code>
   */
  public com.github.ScienceObjectsDB.java_api.models.MetadataOrBuilder getMetadataOrBuilder(
      int index) {
    return metadata_.get(index);
  }

  public static final int CREATED_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp created_;
  /**
   * <pre>
   * When the data object was created
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created = 6;</code>
   * @return Whether the created field is set.
   */
  public boolean hasCreated() {
    return created_ != null;
  }
  /**
   * <pre>
   * When the data object was created
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created = 6;</code>
   * @return The created.
   */
  public com.google.protobuf.Timestamp getCreated() {
    return created_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : created_;
  }
  /**
   * <pre>
   * When the data object was created
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created = 6;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder() {
    return getCreated();
  }

  public static final int LOCATION_FIELD_NUMBER = 7;
  private com.github.ScienceObjectsDB.java_api.models.Location location_;
  /**
   * <pre>
   * Location: Location of the data
   * </pre>
   *
   * <code>.models.Location location = 7;</code>
   * @return Whether the location field is set.
   */
  public boolean hasLocation() {
    return location_ != null;
  }
  /**
   * <pre>
   * Location: Location of the data
   * </pre>
   *
   * <code>.models.Location location = 7;</code>
   * @return The location.
   */
  public com.github.ScienceObjectsDB.java_api.models.Location getLocation() {
    return location_ == null ? com.github.ScienceObjectsDB.java_api.models.Location.getDefaultInstance() : location_;
  }
  /**
   * <pre>
   * Location: Location of the data
   * </pre>
   *
   * <code>.models.Location location = 7;</code>
   */
  public com.github.ScienceObjectsDB.java_api.models.LocationOrBuilder getLocationOrBuilder() {
    return getLocation();
  }

  public static final int ORIGIN_FIELD_NUMBER = 8;
  private com.github.ScienceObjectsDB.java_api.models.Origin origin_;
  /**
   * <pre>
   * Origin: Source of the dataset
   * </pre>
   *
   * <code>.models.Origin origin = 8;</code>
   * @return Whether the origin field is set.
   */
  public boolean hasOrigin() {
    return origin_ != null;
  }
  /**
   * <pre>
   * Origin: Source of the dataset
   * </pre>
   *
   * <code>.models.Origin origin = 8;</code>
   * @return The origin.
   */
  public com.github.ScienceObjectsDB.java_api.models.Origin getOrigin() {
    return origin_ == null ? com.github.ScienceObjectsDB.java_api.models.Origin.getDefaultInstance() : origin_;
  }
  /**
   * <pre>
   * Origin: Source of the dataset
   * </pre>
   *
   * <code>.models.Origin origin = 8;</code>
   */
  public com.github.ScienceObjectsDB.java_api.models.OriginOrBuilder getOriginOrBuilder() {
    return getOrigin();
  }

  public static final int CONTENT_LEN_FIELD_NUMBER = 9;
  private long contentLen_;
  /**
   * <pre>
   * ContentLen: Lenght of the stored dataset
   * </pre>
   *
   * <code>int64 content_len = 9;</code>
   * @return The contentLen.
   */
  public long getContentLen() {
    return contentLen_;
  }

  public static final int UPLOAD_ID_FIELD_NUMBER = 10;
  private volatile java.lang.Object uploadId_;
  /**
   * <code>string upload_id = 10;</code>
   * @return The uploadId.
   */
  public java.lang.String getUploadId() {
    java.lang.Object ref = uploadId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uploadId_ = s;
      return s;
    }
  }
  /**
   * <code>string upload_id = 10;</code>
   * @return The bytes for uploadId.
   */
  public com.google.protobuf.ByteString
      getUploadIdBytes() {
    java.lang.Object ref = uploadId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uploadId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getFilenameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, filename_);
    }
    if (!getFiletypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, filetype_);
    }
    for (int i = 0; i < labels_.size(); i++) {
      output.writeMessage(4, labels_.get(i));
    }
    for (int i = 0; i < metadata_.size(); i++) {
      output.writeMessage(5, metadata_.get(i));
    }
    if (created_ != null) {
      output.writeMessage(6, getCreated());
    }
    if (location_ != null) {
      output.writeMessage(7, getLocation());
    }
    if (origin_ != null) {
      output.writeMessage(8, getOrigin());
    }
    if (contentLen_ != 0L) {
      output.writeInt64(9, contentLen_);
    }
    if (!getUploadIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, uploadId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getFilenameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, filename_);
    }
    if (!getFiletypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, filetype_);
    }
    for (int i = 0; i < labels_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, labels_.get(i));
    }
    for (int i = 0; i < metadata_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, metadata_.get(i));
    }
    if (created_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getCreated());
    }
    if (location_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getLocation());
    }
    if (origin_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getOrigin());
    }
    if (contentLen_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, contentLen_);
    }
    if (!getUploadIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, uploadId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.ScienceObjectsDB.java_api.models.Object)) {
      return super.equals(obj);
    }
    com.github.ScienceObjectsDB.java_api.models.Object other = (com.github.ScienceObjectsDB.java_api.models.Object) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getFilename()
        .equals(other.getFilename())) return false;
    if (!getFiletype()
        .equals(other.getFiletype())) return false;
    if (!getLabelsList()
        .equals(other.getLabelsList())) return false;
    if (!getMetadataList()
        .equals(other.getMetadataList())) return false;
    if (hasCreated() != other.hasCreated()) return false;
    if (hasCreated()) {
      if (!getCreated()
          .equals(other.getCreated())) return false;
    }
    if (hasLocation() != other.hasLocation()) return false;
    if (hasLocation()) {
      if (!getLocation()
          .equals(other.getLocation())) return false;
    }
    if (hasOrigin() != other.hasOrigin()) return false;
    if (hasOrigin()) {
      if (!getOrigin()
          .equals(other.getOrigin())) return false;
    }
    if (getContentLen()
        != other.getContentLen()) return false;
    if (!getUploadId()
        .equals(other.getUploadId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + FILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFilename().hashCode();
    hash = (37 * hash) + FILETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getFiletype().hashCode();
    if (getLabelsCount() > 0) {
      hash = (37 * hash) + LABELS_FIELD_NUMBER;
      hash = (53 * hash) + getLabelsList().hashCode();
    }
    if (getMetadataCount() > 0) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadataList().hashCode();
    }
    if (hasCreated()) {
      hash = (37 * hash) + CREATED_FIELD_NUMBER;
      hash = (53 * hash) + getCreated().hashCode();
    }
    if (hasLocation()) {
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
    }
    if (hasOrigin()) {
      hash = (37 * hash) + ORIGIN_FIELD_NUMBER;
      hash = (53 * hash) + getOrigin().hashCode();
    }
    hash = (37 * hash) + CONTENT_LEN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getContentLen());
    hash = (37 * hash) + UPLOAD_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUploadId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.ScienceObjectsDB.java_api.models.Object parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.ScienceObjectsDB.java_api.models.Object parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.ScienceObjectsDB.java_api.models.Object parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.ScienceObjectsDB.java_api.models.Object parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.ScienceObjectsDB.java_api.models.Object parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.ScienceObjectsDB.java_api.models.Object parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.ScienceObjectsDB.java_api.models.Object parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.ScienceObjectsDB.java_api.models.Object parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.ScienceObjectsDB.java_api.models.Object parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.ScienceObjectsDB.java_api.models.Object parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.ScienceObjectsDB.java_api.models.Object parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.ScienceObjectsDB.java_api.models.Object parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.ScienceObjectsDB.java_api.models.Object prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code models.Object}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:models.Object)
      com.github.ScienceObjectsDB.java_api.models.ObjectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.ScienceObjectsDB.java_api.models.ObjectModels.internal_static_models_Object_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.ScienceObjectsDB.java_api.models.ObjectModels.internal_static_models_Object_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.ScienceObjectsDB.java_api.models.Object.class, com.github.ScienceObjectsDB.java_api.models.Object.Builder.class);
    }

    // Construct using com.github.ScienceObjectsDB.java_api.models.Object.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getLabelsFieldBuilder();
        getMetadataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      filename_ = "";

      filetype_ = "";

      if (labelsBuilder_ == null) {
        labels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        labelsBuilder_.clear();
      }
      if (metadataBuilder_ == null) {
        metadata_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        metadataBuilder_.clear();
      }
      if (createdBuilder_ == null) {
        created_ = null;
      } else {
        created_ = null;
        createdBuilder_ = null;
      }
      if (locationBuilder_ == null) {
        location_ = null;
      } else {
        location_ = null;
        locationBuilder_ = null;
      }
      if (originBuilder_ == null) {
        origin_ = null;
      } else {
        origin_ = null;
        originBuilder_ = null;
      }
      contentLen_ = 0L;

      uploadId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.ScienceObjectsDB.java_api.models.ObjectModels.internal_static_models_Object_descriptor;
    }

    @java.lang.Override
    public com.github.ScienceObjectsDB.java_api.models.Object getDefaultInstanceForType() {
      return com.github.ScienceObjectsDB.java_api.models.Object.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.ScienceObjectsDB.java_api.models.Object build() {
      com.github.ScienceObjectsDB.java_api.models.Object result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.ScienceObjectsDB.java_api.models.Object buildPartial() {
      com.github.ScienceObjectsDB.java_api.models.Object result = new com.github.ScienceObjectsDB.java_api.models.Object(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.filename_ = filename_;
      result.filetype_ = filetype_;
      if (labelsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          labels_ = java.util.Collections.unmodifiableList(labels_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.labels_ = labels_;
      } else {
        result.labels_ = labelsBuilder_.build();
      }
      if (metadataBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          metadata_ = java.util.Collections.unmodifiableList(metadata_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.metadata_ = metadata_;
      } else {
        result.metadata_ = metadataBuilder_.build();
      }
      if (createdBuilder_ == null) {
        result.created_ = created_;
      } else {
        result.created_ = createdBuilder_.build();
      }
      if (locationBuilder_ == null) {
        result.location_ = location_;
      } else {
        result.location_ = locationBuilder_.build();
      }
      if (originBuilder_ == null) {
        result.origin_ = origin_;
      } else {
        result.origin_ = originBuilder_.build();
      }
      result.contentLen_ = contentLen_;
      result.uploadId_ = uploadId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.ScienceObjectsDB.java_api.models.Object) {
        return mergeFrom((com.github.ScienceObjectsDB.java_api.models.Object)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.ScienceObjectsDB.java_api.models.Object other) {
      if (other == com.github.ScienceObjectsDB.java_api.models.Object.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getFilename().isEmpty()) {
        filename_ = other.filename_;
        onChanged();
      }
      if (!other.getFiletype().isEmpty()) {
        filetype_ = other.filetype_;
        onChanged();
      }
      if (labelsBuilder_ == null) {
        if (!other.labels_.isEmpty()) {
          if (labels_.isEmpty()) {
            labels_ = other.labels_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLabelsIsMutable();
            labels_.addAll(other.labels_);
          }
          onChanged();
        }
      } else {
        if (!other.labels_.isEmpty()) {
          if (labelsBuilder_.isEmpty()) {
            labelsBuilder_.dispose();
            labelsBuilder_ = null;
            labels_ = other.labels_;
            bitField0_ = (bitField0_ & ~0x00000001);
            labelsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLabelsFieldBuilder() : null;
          } else {
            labelsBuilder_.addAllMessages(other.labels_);
          }
        }
      }
      if (metadataBuilder_ == null) {
        if (!other.metadata_.isEmpty()) {
          if (metadata_.isEmpty()) {
            metadata_ = other.metadata_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMetadataIsMutable();
            metadata_.addAll(other.metadata_);
          }
          onChanged();
        }
      } else {
        if (!other.metadata_.isEmpty()) {
          if (metadataBuilder_.isEmpty()) {
            metadataBuilder_.dispose();
            metadataBuilder_ = null;
            metadata_ = other.metadata_;
            bitField0_ = (bitField0_ & ~0x00000002);
            metadataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMetadataFieldBuilder() : null;
          } else {
            metadataBuilder_.addAllMessages(other.metadata_);
          }
        }
      }
      if (other.hasCreated()) {
        mergeCreated(other.getCreated());
      }
      if (other.hasLocation()) {
        mergeLocation(other.getLocation());
      }
      if (other.hasOrigin()) {
        mergeOrigin(other.getOrigin());
      }
      if (other.getContentLen() != 0L) {
        setContentLen(other.getContentLen());
      }
      if (!other.getUploadId().isEmpty()) {
        uploadId_ = other.uploadId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.ScienceObjectsDB.java_api.models.Object parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.ScienceObjectsDB.java_api.models.Object) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <pre>
     *ID of the entity
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *ID of the entity
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *ID of the entity
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *ID of the entity
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *ID of the entity
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object filename_ = "";
    /**
     * <pre>
     * Filename: Name of the original file e.g.: mydata.json
     * </pre>
     *
     * <code>string filename = 2;</code>
     * @return The filename.
     */
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filename_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Filename: Name of the original file e.g.: mydata.json
     * </pre>
     *
     * <code>string filename = 2;</code>
     * @return The bytes for filename.
     */
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Filename: Name of the original file e.g.: mydata.json
     * </pre>
     *
     * <code>string filename = 2;</code>
     * @param value The filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilename(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      filename_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Filename: Name of the original file e.g.: mydata.json
     * </pre>
     *
     * <code>string filename = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilename() {
      
      filename_ = getDefaultInstance().getFilename();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Filename: Name of the original file e.g.: mydata.json
     * </pre>
     *
     * <code>string filename = 2;</code>
     * @param value The bytes for filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilenameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      filename_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object filetype_ = "";
    /**
     * <pre>
     * Filetype: Type of the stored file, e.g.: json, gbff,...
     * </pre>
     *
     * <code>string filetype = 3;</code>
     * @return The filetype.
     */
    public java.lang.String getFiletype() {
      java.lang.Object ref = filetype_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filetype_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Filetype: Type of the stored file, e.g.: json, gbff,...
     * </pre>
     *
     * <code>string filetype = 3;</code>
     * @return The bytes for filetype.
     */
    public com.google.protobuf.ByteString
        getFiletypeBytes() {
      java.lang.Object ref = filetype_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filetype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Filetype: Type of the stored file, e.g.: json, gbff,...
     * </pre>
     *
     * <code>string filetype = 3;</code>
     * @param value The filetype to set.
     * @return This builder for chaining.
     */
    public Builder setFiletype(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      filetype_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Filetype: Type of the stored file, e.g.: json, gbff,...
     * </pre>
     *
     * <code>string filetype = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFiletype() {
      
      filetype_ = getDefaultInstance().getFiletype();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Filetype: Type of the stored file, e.g.: json, gbff,...
     * </pre>
     *
     * <code>string filetype = 3;</code>
     * @param value The bytes for filetype to set.
     * @return This builder for chaining.
     */
    public Builder setFiletypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      filetype_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.github.ScienceObjectsDB.java_api.models.Label> labels_ =
      java.util.Collections.emptyList();
    private void ensureLabelsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        labels_ = new java.util.ArrayList<com.github.ScienceObjectsDB.java_api.models.Label>(labels_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.ScienceObjectsDB.java_api.models.Label, com.github.ScienceObjectsDB.java_api.models.Label.Builder, com.github.ScienceObjectsDB.java_api.models.LabelOrBuilder> labelsBuilder_;

    /**
     * <code>repeated .models.Label labels = 4;</code>
     */
    public java.util.List<com.github.ScienceObjectsDB.java_api.models.Label> getLabelsList() {
      if (labelsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(labels_);
      } else {
        return labelsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .models.Label labels = 4;</code>
     */
    public int getLabelsCount() {
      if (labelsBuilder_ == null) {
        return labels_.size();
      } else {
        return labelsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .models.Label labels = 4;</code>
     */
    public com.github.ScienceObjectsDB.java_api.models.Label getLabels(int index) {
      if (labelsBuilder_ == null) {
        return labels_.get(index);
      } else {
        return labelsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .models.Label labels = 4;</code>
     */
    public Builder setLabels(
        int index, com.github.ScienceObjectsDB.java_api.models.Label value) {
      if (labelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLabelsIsMutable();
        labels_.set(index, value);
        onChanged();
      } else {
        labelsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .models.Label labels = 4;</code>
     */
    public Builder setLabels(
        int index, com.github.ScienceObjectsDB.java_api.models.Label.Builder builderForValue) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        labels_.set(index, builderForValue.build());
        onChanged();
      } else {
        labelsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .models.Label labels = 4;</code>
     */
    public Builder addLabels(com.github.ScienceObjectsDB.java_api.models.Label value) {
      if (labelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLabelsIsMutable();
        labels_.add(value);
        onChanged();
      } else {
        labelsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .models.Label labels = 4;</code>
     */
    public Builder addLabels(
        int index, com.github.ScienceObjectsDB.java_api.models.Label value) {
      if (labelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLabelsIsMutable();
        labels_.add(index, value);
        onChanged();
      } else {
        labelsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .models.Label labels = 4;</code>
     */
    public Builder addLabels(
        com.github.ScienceObjectsDB.java_api.models.Label.Builder builderForValue) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        labels_.add(builderForValue.build());
        onChanged();
      } else {
        labelsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .models.Label labels = 4;</code>
     */
    public Builder addLabels(
        int index, com.github.ScienceObjectsDB.java_api.models.Label.Builder builderForValue) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        labels_.add(index, builderForValue.build());
        onChanged();
      } else {
        labelsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .models.Label labels = 4;</code>
     */
    public Builder addAllLabels(
        java.lang.Iterable<? extends com.github.ScienceObjectsDB.java_api.models.Label> values) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, labels_);
        onChanged();
      } else {
        labelsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .models.Label labels = 4;</code>
     */
    public Builder clearLabels() {
      if (labelsBuilder_ == null) {
        labels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        labelsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .models.Label labels = 4;</code>
     */
    public Builder removeLabels(int index) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        labels_.remove(index);
        onChanged();
      } else {
        labelsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .models.Label labels = 4;</code>
     */
    public com.github.ScienceObjectsDB.java_api.models.Label.Builder getLabelsBuilder(
        int index) {
      return getLabelsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .models.Label labels = 4;</code>
     */
    public com.github.ScienceObjectsDB.java_api.models.LabelOrBuilder getLabelsOrBuilder(
        int index) {
      if (labelsBuilder_ == null) {
        return labels_.get(index);  } else {
        return labelsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .models.Label labels = 4;</code>
     */
    public java.util.List<? extends com.github.ScienceObjectsDB.java_api.models.LabelOrBuilder> 
         getLabelsOrBuilderList() {
      if (labelsBuilder_ != null) {
        return labelsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(labels_);
      }
    }
    /**
     * <code>repeated .models.Label labels = 4;</code>
     */
    public com.github.ScienceObjectsDB.java_api.models.Label.Builder addLabelsBuilder() {
      return getLabelsFieldBuilder().addBuilder(
          com.github.ScienceObjectsDB.java_api.models.Label.getDefaultInstance());
    }
    /**
     * <code>repeated .models.Label labels = 4;</code>
     */
    public com.github.ScienceObjectsDB.java_api.models.Label.Builder addLabelsBuilder(
        int index) {
      return getLabelsFieldBuilder().addBuilder(
          index, com.github.ScienceObjectsDB.java_api.models.Label.getDefaultInstance());
    }
    /**
     * <code>repeated .models.Label labels = 4;</code>
     */
    public java.util.List<com.github.ScienceObjectsDB.java_api.models.Label.Builder> 
         getLabelsBuilderList() {
      return getLabelsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.ScienceObjectsDB.java_api.models.Label, com.github.ScienceObjectsDB.java_api.models.Label.Builder, com.github.ScienceObjectsDB.java_api.models.LabelOrBuilder> 
        getLabelsFieldBuilder() {
      if (labelsBuilder_ == null) {
        labelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.ScienceObjectsDB.java_api.models.Label, com.github.ScienceObjectsDB.java_api.models.Label.Builder, com.github.ScienceObjectsDB.java_api.models.LabelOrBuilder>(
                labels_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        labels_ = null;
      }
      return labelsBuilder_;
    }

    private java.util.List<com.github.ScienceObjectsDB.java_api.models.Metadata> metadata_ =
      java.util.Collections.emptyList();
    private void ensureMetadataIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        metadata_ = new java.util.ArrayList<com.github.ScienceObjectsDB.java_api.models.Metadata>(metadata_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.ScienceObjectsDB.java_api.models.Metadata, com.github.ScienceObjectsDB.java_api.models.Metadata.Builder, com.github.ScienceObjectsDB.java_api.models.MetadataOrBuilder> metadataBuilder_;

    /**
     * <code>repeated .models.Metadata metadata = 5;</code>
     */
    public java.util.List<com.github.ScienceObjectsDB.java_api.models.Metadata> getMetadataList() {
      if (metadataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(metadata_);
      } else {
        return metadataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .models.Metadata metadata = 5;</code>
     */
    public int getMetadataCount() {
      if (metadataBuilder_ == null) {
        return metadata_.size();
      } else {
        return metadataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .models.Metadata metadata = 5;</code>
     */
    public com.github.ScienceObjectsDB.java_api.models.Metadata getMetadata(int index) {
      if (metadataBuilder_ == null) {
        return metadata_.get(index);
      } else {
        return metadataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .models.Metadata metadata = 5;</code>
     */
    public Builder setMetadata(
        int index, com.github.ScienceObjectsDB.java_api.models.Metadata value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetadataIsMutable();
        metadata_.set(index, value);
        onChanged();
      } else {
        metadataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .models.Metadata metadata = 5;</code>
     */
    public Builder setMetadata(
        int index, com.github.ScienceObjectsDB.java_api.models.Metadata.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        ensureMetadataIsMutable();
        metadata_.set(index, builderForValue.build());
        onChanged();
      } else {
        metadataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .models.Metadata metadata = 5;</code>
     */
    public Builder addMetadata(com.github.ScienceObjectsDB.java_api.models.Metadata value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetadataIsMutable();
        metadata_.add(value);
        onChanged();
      } else {
        metadataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .models.Metadata metadata = 5;</code>
     */
    public Builder addMetadata(
        int index, com.github.ScienceObjectsDB.java_api.models.Metadata value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetadataIsMutable();
        metadata_.add(index, value);
        onChanged();
      } else {
        metadataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .models.Metadata metadata = 5;</code>
     */
    public Builder addMetadata(
        com.github.ScienceObjectsDB.java_api.models.Metadata.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        ensureMetadataIsMutable();
        metadata_.add(builderForValue.build());
        onChanged();
      } else {
        metadataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .models.Metadata metadata = 5;</code>
     */
    public Builder addMetadata(
        int index, com.github.ScienceObjectsDB.java_api.models.Metadata.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        ensureMetadataIsMutable();
        metadata_.add(index, builderForValue.build());
        onChanged();
      } else {
        metadataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .models.Metadata metadata = 5;</code>
     */
    public Builder addAllMetadata(
        java.lang.Iterable<? extends com.github.ScienceObjectsDB.java_api.models.Metadata> values) {
      if (metadataBuilder_ == null) {
        ensureMetadataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, metadata_);
        onChanged();
      } else {
        metadataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .models.Metadata metadata = 5;</code>
     */
    public Builder clearMetadata() {
      if (metadataBuilder_ == null) {
        metadata_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        metadataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .models.Metadata metadata = 5;</code>
     */
    public Builder removeMetadata(int index) {
      if (metadataBuilder_ == null) {
        ensureMetadataIsMutable();
        metadata_.remove(index);
        onChanged();
      } else {
        metadataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .models.Metadata metadata = 5;</code>
     */
    public com.github.ScienceObjectsDB.java_api.models.Metadata.Builder getMetadataBuilder(
        int index) {
      return getMetadataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .models.Metadata metadata = 5;</code>
     */
    public com.github.ScienceObjectsDB.java_api.models.MetadataOrBuilder getMetadataOrBuilder(
        int index) {
      if (metadataBuilder_ == null) {
        return metadata_.get(index);  } else {
        return metadataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .models.Metadata metadata = 5;</code>
     */
    public java.util.List<? extends com.github.ScienceObjectsDB.java_api.models.MetadataOrBuilder> 
         getMetadataOrBuilderList() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(metadata_);
      }
    }
    /**
     * <code>repeated .models.Metadata metadata = 5;</code>
     */
    public com.github.ScienceObjectsDB.java_api.models.Metadata.Builder addMetadataBuilder() {
      return getMetadataFieldBuilder().addBuilder(
          com.github.ScienceObjectsDB.java_api.models.Metadata.getDefaultInstance());
    }
    /**
     * <code>repeated .models.Metadata metadata = 5;</code>
     */
    public com.github.ScienceObjectsDB.java_api.models.Metadata.Builder addMetadataBuilder(
        int index) {
      return getMetadataFieldBuilder().addBuilder(
          index, com.github.ScienceObjectsDB.java_api.models.Metadata.getDefaultInstance());
    }
    /**
     * <code>repeated .models.Metadata metadata = 5;</code>
     */
    public java.util.List<com.github.ScienceObjectsDB.java_api.models.Metadata.Builder> 
         getMetadataBuilderList() {
      return getMetadataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.ScienceObjectsDB.java_api.models.Metadata, com.github.ScienceObjectsDB.java_api.models.Metadata.Builder, com.github.ScienceObjectsDB.java_api.models.MetadataOrBuilder> 
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.ScienceObjectsDB.java_api.models.Metadata, com.github.ScienceObjectsDB.java_api.models.Metadata.Builder, com.github.ScienceObjectsDB.java_api.models.MetadataOrBuilder>(
                metadata_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }

    private com.google.protobuf.Timestamp created_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdBuilder_;
    /**
     * <pre>
     * When the data object was created
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created = 6;</code>
     * @return Whether the created field is set.
     */
    public boolean hasCreated() {
      return createdBuilder_ != null || created_ != null;
    }
    /**
     * <pre>
     * When the data object was created
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created = 6;</code>
     * @return The created.
     */
    public com.google.protobuf.Timestamp getCreated() {
      if (createdBuilder_ == null) {
        return created_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : created_;
      } else {
        return createdBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * When the data object was created
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created = 6;</code>
     */
    public Builder setCreated(com.google.protobuf.Timestamp value) {
      if (createdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        created_ = value;
        onChanged();
      } else {
        createdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * When the data object was created
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created = 6;</code>
     */
    public Builder setCreated(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdBuilder_ == null) {
        created_ = builderForValue.build();
        onChanged();
      } else {
        createdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * When the data object was created
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created = 6;</code>
     */
    public Builder mergeCreated(com.google.protobuf.Timestamp value) {
      if (createdBuilder_ == null) {
        if (created_ != null) {
          created_ =
            com.google.protobuf.Timestamp.newBuilder(created_).mergeFrom(value).buildPartial();
        } else {
          created_ = value;
        }
        onChanged();
      } else {
        createdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * When the data object was created
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created = 6;</code>
     */
    public Builder clearCreated() {
      if (createdBuilder_ == null) {
        created_ = null;
        onChanged();
      } else {
        created_ = null;
        createdBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * When the data object was created
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created = 6;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedBuilder() {
      
      onChanged();
      return getCreatedFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * When the data object was created
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder() {
      if (createdBuilder_ != null) {
        return createdBuilder_.getMessageOrBuilder();
      } else {
        return created_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : created_;
      }
    }
    /**
     * <pre>
     * When the data object was created
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedFieldBuilder() {
      if (createdBuilder_ == null) {
        createdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreated(),
                getParentForChildren(),
                isClean());
        created_ = null;
      }
      return createdBuilder_;
    }

    private com.github.ScienceObjectsDB.java_api.models.Location location_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ScienceObjectsDB.java_api.models.Location, com.github.ScienceObjectsDB.java_api.models.Location.Builder, com.github.ScienceObjectsDB.java_api.models.LocationOrBuilder> locationBuilder_;
    /**
     * <pre>
     * Location: Location of the data
     * </pre>
     *
     * <code>.models.Location location = 7;</code>
     * @return Whether the location field is set.
     */
    public boolean hasLocation() {
      return locationBuilder_ != null || location_ != null;
    }
    /**
     * <pre>
     * Location: Location of the data
     * </pre>
     *
     * <code>.models.Location location = 7;</code>
     * @return The location.
     */
    public com.github.ScienceObjectsDB.java_api.models.Location getLocation() {
      if (locationBuilder_ == null) {
        return location_ == null ? com.github.ScienceObjectsDB.java_api.models.Location.getDefaultInstance() : location_;
      } else {
        return locationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Location: Location of the data
     * </pre>
     *
     * <code>.models.Location location = 7;</code>
     */
    public Builder setLocation(com.github.ScienceObjectsDB.java_api.models.Location value) {
      if (locationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        location_ = value;
        onChanged();
      } else {
        locationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Location: Location of the data
     * </pre>
     *
     * <code>.models.Location location = 7;</code>
     */
    public Builder setLocation(
        com.github.ScienceObjectsDB.java_api.models.Location.Builder builderForValue) {
      if (locationBuilder_ == null) {
        location_ = builderForValue.build();
        onChanged();
      } else {
        locationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Location: Location of the data
     * </pre>
     *
     * <code>.models.Location location = 7;</code>
     */
    public Builder mergeLocation(com.github.ScienceObjectsDB.java_api.models.Location value) {
      if (locationBuilder_ == null) {
        if (location_ != null) {
          location_ =
            com.github.ScienceObjectsDB.java_api.models.Location.newBuilder(location_).mergeFrom(value).buildPartial();
        } else {
          location_ = value;
        }
        onChanged();
      } else {
        locationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Location: Location of the data
     * </pre>
     *
     * <code>.models.Location location = 7;</code>
     */
    public Builder clearLocation() {
      if (locationBuilder_ == null) {
        location_ = null;
        onChanged();
      } else {
        location_ = null;
        locationBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Location: Location of the data
     * </pre>
     *
     * <code>.models.Location location = 7;</code>
     */
    public com.github.ScienceObjectsDB.java_api.models.Location.Builder getLocationBuilder() {
      
      onChanged();
      return getLocationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Location: Location of the data
     * </pre>
     *
     * <code>.models.Location location = 7;</code>
     */
    public com.github.ScienceObjectsDB.java_api.models.LocationOrBuilder getLocationOrBuilder() {
      if (locationBuilder_ != null) {
        return locationBuilder_.getMessageOrBuilder();
      } else {
        return location_ == null ?
            com.github.ScienceObjectsDB.java_api.models.Location.getDefaultInstance() : location_;
      }
    }
    /**
     * <pre>
     * Location: Location of the data
     * </pre>
     *
     * <code>.models.Location location = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ScienceObjectsDB.java_api.models.Location, com.github.ScienceObjectsDB.java_api.models.Location.Builder, com.github.ScienceObjectsDB.java_api.models.LocationOrBuilder> 
        getLocationFieldBuilder() {
      if (locationBuilder_ == null) {
        locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.ScienceObjectsDB.java_api.models.Location, com.github.ScienceObjectsDB.java_api.models.Location.Builder, com.github.ScienceObjectsDB.java_api.models.LocationOrBuilder>(
                getLocation(),
                getParentForChildren(),
                isClean());
        location_ = null;
      }
      return locationBuilder_;
    }

    private com.github.ScienceObjectsDB.java_api.models.Origin origin_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ScienceObjectsDB.java_api.models.Origin, com.github.ScienceObjectsDB.java_api.models.Origin.Builder, com.github.ScienceObjectsDB.java_api.models.OriginOrBuilder> originBuilder_;
    /**
     * <pre>
     * Origin: Source of the dataset
     * </pre>
     *
     * <code>.models.Origin origin = 8;</code>
     * @return Whether the origin field is set.
     */
    public boolean hasOrigin() {
      return originBuilder_ != null || origin_ != null;
    }
    /**
     * <pre>
     * Origin: Source of the dataset
     * </pre>
     *
     * <code>.models.Origin origin = 8;</code>
     * @return The origin.
     */
    public com.github.ScienceObjectsDB.java_api.models.Origin getOrigin() {
      if (originBuilder_ == null) {
        return origin_ == null ? com.github.ScienceObjectsDB.java_api.models.Origin.getDefaultInstance() : origin_;
      } else {
        return originBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Origin: Source of the dataset
     * </pre>
     *
     * <code>.models.Origin origin = 8;</code>
     */
    public Builder setOrigin(com.github.ScienceObjectsDB.java_api.models.Origin value) {
      if (originBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        origin_ = value;
        onChanged();
      } else {
        originBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Origin: Source of the dataset
     * </pre>
     *
     * <code>.models.Origin origin = 8;</code>
     */
    public Builder setOrigin(
        com.github.ScienceObjectsDB.java_api.models.Origin.Builder builderForValue) {
      if (originBuilder_ == null) {
        origin_ = builderForValue.build();
        onChanged();
      } else {
        originBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Origin: Source of the dataset
     * </pre>
     *
     * <code>.models.Origin origin = 8;</code>
     */
    public Builder mergeOrigin(com.github.ScienceObjectsDB.java_api.models.Origin value) {
      if (originBuilder_ == null) {
        if (origin_ != null) {
          origin_ =
            com.github.ScienceObjectsDB.java_api.models.Origin.newBuilder(origin_).mergeFrom(value).buildPartial();
        } else {
          origin_ = value;
        }
        onChanged();
      } else {
        originBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Origin: Source of the dataset
     * </pre>
     *
     * <code>.models.Origin origin = 8;</code>
     */
    public Builder clearOrigin() {
      if (originBuilder_ == null) {
        origin_ = null;
        onChanged();
      } else {
        origin_ = null;
        originBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Origin: Source of the dataset
     * </pre>
     *
     * <code>.models.Origin origin = 8;</code>
     */
    public com.github.ScienceObjectsDB.java_api.models.Origin.Builder getOriginBuilder() {
      
      onChanged();
      return getOriginFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Origin: Source of the dataset
     * </pre>
     *
     * <code>.models.Origin origin = 8;</code>
     */
    public com.github.ScienceObjectsDB.java_api.models.OriginOrBuilder getOriginOrBuilder() {
      if (originBuilder_ != null) {
        return originBuilder_.getMessageOrBuilder();
      } else {
        return origin_ == null ?
            com.github.ScienceObjectsDB.java_api.models.Origin.getDefaultInstance() : origin_;
      }
    }
    /**
     * <pre>
     * Origin: Source of the dataset
     * </pre>
     *
     * <code>.models.Origin origin = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.ScienceObjectsDB.java_api.models.Origin, com.github.ScienceObjectsDB.java_api.models.Origin.Builder, com.github.ScienceObjectsDB.java_api.models.OriginOrBuilder> 
        getOriginFieldBuilder() {
      if (originBuilder_ == null) {
        originBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.ScienceObjectsDB.java_api.models.Origin, com.github.ScienceObjectsDB.java_api.models.Origin.Builder, com.github.ScienceObjectsDB.java_api.models.OriginOrBuilder>(
                getOrigin(),
                getParentForChildren(),
                isClean());
        origin_ = null;
      }
      return originBuilder_;
    }

    private long contentLen_ ;
    /**
     * <pre>
     * ContentLen: Lenght of the stored dataset
     * </pre>
     *
     * <code>int64 content_len = 9;</code>
     * @return The contentLen.
     */
    public long getContentLen() {
      return contentLen_;
    }
    /**
     * <pre>
     * ContentLen: Lenght of the stored dataset
     * </pre>
     *
     * <code>int64 content_len = 9;</code>
     * @param value The contentLen to set.
     * @return This builder for chaining.
     */
    public Builder setContentLen(long value) {
      
      contentLen_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ContentLen: Lenght of the stored dataset
     * </pre>
     *
     * <code>int64 content_len = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearContentLen() {
      
      contentLen_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object uploadId_ = "";
    /**
     * <code>string upload_id = 10;</code>
     * @return The uploadId.
     */
    public java.lang.String getUploadId() {
      java.lang.Object ref = uploadId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uploadId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string upload_id = 10;</code>
     * @return The bytes for uploadId.
     */
    public com.google.protobuf.ByteString
        getUploadIdBytes() {
      java.lang.Object ref = uploadId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uploadId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string upload_id = 10;</code>
     * @param value The uploadId to set.
     * @return This builder for chaining.
     */
    public Builder setUploadId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uploadId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string upload_id = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearUploadId() {
      
      uploadId_ = getDefaultInstance().getUploadId();
      onChanged();
      return this;
    }
    /**
     * <code>string upload_id = 10;</code>
     * @param value The bytes for uploadId to set.
     * @return This builder for chaining.
     */
    public Builder setUploadIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uploadId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:models.Object)
  }

  // @@protoc_insertion_point(class_scope:models.Object)
  private static final com.github.ScienceObjectsDB.java_api.models.Object DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.ScienceObjectsDB.java_api.models.Object();
  }

  public static com.github.ScienceObjectsDB.java_api.models.Object getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Object>
      PARSER = new com.google.protobuf.AbstractParser<Object>() {
    @java.lang.Override
    public Object parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Object(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Object> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Object> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.ScienceObjectsDB.java_api.models.Object getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

