// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sciobjsdb/api/storage/models/v1/common_models.proto

package com.github.ScienceObjectsDB.java_api.sciobjsdb.api.storage.models.v1;

public interface IndexOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sciobjsdb.api.storage.models.v1.Index)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 start_byte = 1 [json_name = "startByte"];</code>
   * @return The startByte.
   */
  long getStartByte();

  /**
   * <code>int64 end_byte = 2 [json_name = "endByte"];</code>
   * @return The endByte.
   */
  long getEndByte();
}
