// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/models/v1/object_models.proto

package com.github.ScienceObjectsDB.java_api.api.models.v1;

/**
 * Protobuf type {@code api.models.v1.ObjectGroup}
 */
public  final class ObjectGroup extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.models.v1.ObjectGroup)
    ObjectGroupOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ObjectGroup.newBuilder() to construct.
  private ObjectGroup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ObjectGroup() {
    id_ = "";
    name_ = "";
    description_ = "";
    datasetId_ = "";
    projectId_ = "";
    labels_ = java.util.Collections.emptyList();
    metadata_ = java.util.Collections.emptyList();
    status_ = 0;
    objects_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ObjectGroup(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            datasetId_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            projectId_ = s;
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              labels_ = new java.util.ArrayList<com.github.ScienceObjectsDB.java_api.api.models.v1.Label>();
              mutable_bitField0_ |= 0x00000020;
            }
            labels_.add(
                input.readMessage(com.github.ScienceObjectsDB.java_api.api.models.v1.Label.parser(), extensionRegistry));
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              metadata_ = new java.util.ArrayList<com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata>();
              mutable_bitField0_ |= 0x00000040;
            }
            metadata_.add(
                input.readMessage(com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata.parser(), extensionRegistry));
            break;
          }
          case 64: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 74: {
            if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
              objects_ = new java.util.ArrayList<com.github.ScienceObjectsDB.java_api.api.models.v1.Object>();
              mutable_bitField0_ |= 0x00000100;
            }
            objects_.add(
                input.readMessage(com.github.ScienceObjectsDB.java_api.api.models.v1.Object.parser(), extensionRegistry));
            break;
          }
          case 82: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (generated_ != null) {
              subBuilder = generated_.toBuilder();
            }
            generated_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(generated_);
              generated_ = subBuilder.buildPartial();
            }

            break;
          }
          case 90: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (created_ != null) {
              subBuilder = created_.toBuilder();
            }
            created_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(created_);
              created_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        labels_ = java.util.Collections.unmodifiableList(labels_);
      }
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        metadata_ = java.util.Collections.unmodifiableList(metadata_);
      }
      if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
        objects_ = java.util.Collections.unmodifiableList(objects_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectModels.internal_static_api_models_v1_ObjectGroup_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectModels.internal_static_api_models_v1_ObjectGroup_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup.class, com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1[json_name = "id"];</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1[json_name = "id"];</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2[json_name = "name"];</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2[json_name = "name"];</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 3[json_name = "description"];</code>
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 3[json_name = "description"];</code>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATASET_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object datasetId_;
  /**
   * <code>string dataset_id = 4[json_name = "datasetId"];</code>
   */
  public java.lang.String getDatasetId() {
    java.lang.Object ref = datasetId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      datasetId_ = s;
      return s;
    }
  }
  /**
   * <code>string dataset_id = 4[json_name = "datasetId"];</code>
   */
  public com.google.protobuf.ByteString
      getDatasetIdBytes() {
    java.lang.Object ref = datasetId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      datasetId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROJECT_ID_FIELD_NUMBER = 5;
  private volatile java.lang.Object projectId_;
  /**
   * <code>string project_id = 5[json_name = "projectId"];</code>
   */
  public java.lang.String getProjectId() {
    java.lang.Object ref = projectId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      projectId_ = s;
      return s;
    }
  }
  /**
   * <code>string project_id = 5[json_name = "projectId"];</code>
   */
  public com.google.protobuf.ByteString
      getProjectIdBytes() {
    java.lang.Object ref = projectId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      projectId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LABELS_FIELD_NUMBER = 6;
  private java.util.List<com.github.ScienceObjectsDB.java_api.api.models.v1.Label> labels_;
  /**
   * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
   */
  public java.util.List<com.github.ScienceObjectsDB.java_api.api.models.v1.Label> getLabelsList() {
    return labels_;
  }
  /**
   * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
   */
  public java.util.List<? extends com.github.ScienceObjectsDB.java_api.api.models.v1.LabelOrBuilder> 
      getLabelsOrBuilderList() {
    return labels_;
  }
  /**
   * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
   */
  public int getLabelsCount() {
    return labels_.size();
  }
  /**
   * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
   */
  public com.github.ScienceObjectsDB.java_api.api.models.v1.Label getLabels(int index) {
    return labels_.get(index);
  }
  /**
   * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
   */
  public com.github.ScienceObjectsDB.java_api.api.models.v1.LabelOrBuilder getLabelsOrBuilder(
      int index) {
    return labels_.get(index);
  }

  public static final int METADATA_FIELD_NUMBER = 7;
  private java.util.List<com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata> metadata_;
  /**
   * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
   */
  public java.util.List<com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata> getMetadataList() {
    return metadata_;
  }
  /**
   * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
   */
  public java.util.List<? extends com.github.ScienceObjectsDB.java_api.api.models.v1.MetadataOrBuilder> 
      getMetadataOrBuilderList() {
    return metadata_;
  }
  /**
   * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
   */
  public int getMetadataCount() {
    return metadata_.size();
  }
  /**
   * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
   */
  public com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata getMetadata(int index) {
    return metadata_.get(index);
  }
  /**
   * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
   */
  public com.github.ScienceObjectsDB.java_api.api.models.v1.MetadataOrBuilder getMetadataOrBuilder(
      int index) {
    return metadata_.get(index);
  }

  public static final int STATUS_FIELD_NUMBER = 8;
  private int status_;
  /**
   * <code>.api.models.v1.Status status = 8[json_name = "status"];</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.api.models.v1.Status status = 8[json_name = "status"];</code>
   */
  public com.github.ScienceObjectsDB.java_api.api.models.v1.Status getStatus() {
    @SuppressWarnings("deprecation")
    com.github.ScienceObjectsDB.java_api.api.models.v1.Status result = com.github.ScienceObjectsDB.java_api.api.models.v1.Status.valueOf(status_);
    return result == null ? com.github.ScienceObjectsDB.java_api.api.models.v1.Status.UNRECOGNIZED : result;
  }

  public static final int OBJECTS_FIELD_NUMBER = 9;
  private java.util.List<com.github.ScienceObjectsDB.java_api.api.models.v1.Object> objects_;
  /**
   * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
   */
  public java.util.List<com.github.ScienceObjectsDB.java_api.api.models.v1.Object> getObjectsList() {
    return objects_;
  }
  /**
   * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
   */
  public java.util.List<? extends com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectOrBuilder> 
      getObjectsOrBuilderList() {
    return objects_;
  }
  /**
   * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
   */
  public int getObjectsCount() {
    return objects_.size();
  }
  /**
   * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
   */
  public com.github.ScienceObjectsDB.java_api.api.models.v1.Object getObjects(int index) {
    return objects_.get(index);
  }
  /**
   * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
   */
  public com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectOrBuilder getObjectsOrBuilder(
      int index) {
    return objects_.get(index);
  }

  public static final int GENERATED_FIELD_NUMBER = 10;
  private com.google.protobuf.Timestamp generated_;
  /**
   * <code>.google.protobuf.Timestamp generated = 10[json_name = "generated"];</code>
   */
  public boolean hasGenerated() {
    return generated_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp generated = 10[json_name = "generated"];</code>
   */
  public com.google.protobuf.Timestamp getGenerated() {
    return generated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : generated_;
  }
  /**
   * <code>.google.protobuf.Timestamp generated = 10[json_name = "generated"];</code>
   */
  public com.google.protobuf.TimestampOrBuilder getGeneratedOrBuilder() {
    return getGenerated();
  }

  public static final int CREATED_FIELD_NUMBER = 11;
  private com.google.protobuf.Timestamp created_;
  /**
   * <code>.google.protobuf.Timestamp created = 11[json_name = "created"];</code>
   */
  public boolean hasCreated() {
    return created_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp created = 11[json_name = "created"];</code>
   */
  public com.google.protobuf.Timestamp getCreated() {
    return created_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : created_;
  }
  /**
   * <code>.google.protobuf.Timestamp created = 11[json_name = "created"];</code>
   */
  public com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder() {
    return getCreated();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
    }
    if (!getDatasetIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, datasetId_);
    }
    if (!getProjectIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, projectId_);
    }
    for (int i = 0; i < labels_.size(); i++) {
      output.writeMessage(6, labels_.get(i));
    }
    for (int i = 0; i < metadata_.size(); i++) {
      output.writeMessage(7, metadata_.get(i));
    }
    if (status_ != com.github.ScienceObjectsDB.java_api.api.models.v1.Status.INITIATING.getNumber()) {
      output.writeEnum(8, status_);
    }
    for (int i = 0; i < objects_.size(); i++) {
      output.writeMessage(9, objects_.get(i));
    }
    if (generated_ != null) {
      output.writeMessage(10, getGenerated());
    }
    if (created_ != null) {
      output.writeMessage(11, getCreated());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
    }
    if (!getDatasetIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, datasetId_);
    }
    if (!getProjectIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, projectId_);
    }
    for (int i = 0; i < labels_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, labels_.get(i));
    }
    for (int i = 0; i < metadata_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, metadata_.get(i));
    }
    if (status_ != com.github.ScienceObjectsDB.java_api.api.models.v1.Status.INITIATING.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(8, status_);
    }
    for (int i = 0; i < objects_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, objects_.get(i));
    }
    if (generated_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getGenerated());
    }
    if (created_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getCreated());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup)) {
      return super.equals(obj);
    }
    com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup other = (com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup) obj;

    boolean result = true;
    result = result && getId()
        .equals(other.getId());
    result = result && getName()
        .equals(other.getName());
    result = result && getDescription()
        .equals(other.getDescription());
    result = result && getDatasetId()
        .equals(other.getDatasetId());
    result = result && getProjectId()
        .equals(other.getProjectId());
    result = result && getLabelsList()
        .equals(other.getLabelsList());
    result = result && getMetadataList()
        .equals(other.getMetadataList());
    result = result && status_ == other.status_;
    result = result && getObjectsList()
        .equals(other.getObjectsList());
    result = result && (hasGenerated() == other.hasGenerated());
    if (hasGenerated()) {
      result = result && getGenerated()
          .equals(other.getGenerated());
    }
    result = result && (hasCreated() == other.hasCreated());
    if (hasCreated()) {
      result = result && getCreated()
          .equals(other.getCreated());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + DATASET_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDatasetId().hashCode();
    hash = (37 * hash) + PROJECT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getProjectId().hashCode();
    if (getLabelsCount() > 0) {
      hash = (37 * hash) + LABELS_FIELD_NUMBER;
      hash = (53 * hash) + getLabelsList().hashCode();
    }
    if (getMetadataCount() > 0) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadataList().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (getObjectsCount() > 0) {
      hash = (37 * hash) + OBJECTS_FIELD_NUMBER;
      hash = (53 * hash) + getObjectsList().hashCode();
    }
    if (hasGenerated()) {
      hash = (37 * hash) + GENERATED_FIELD_NUMBER;
      hash = (53 * hash) + getGenerated().hashCode();
    }
    if (hasCreated()) {
      hash = (37 * hash) + CREATED_FIELD_NUMBER;
      hash = (53 * hash) + getCreated().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.models.v1.ObjectGroup}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.models.v1.ObjectGroup)
      com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroupOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectModels.internal_static_api_models_v1_ObjectGroup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectModels.internal_static_api_models_v1_ObjectGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup.class, com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup.Builder.class);
    }

    // Construct using com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getLabelsFieldBuilder();
        getMetadataFieldBuilder();
        getObjectsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      name_ = "";

      description_ = "";

      datasetId_ = "";

      projectId_ = "";

      if (labelsBuilder_ == null) {
        labels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        labelsBuilder_.clear();
      }
      if (metadataBuilder_ == null) {
        metadata_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
      } else {
        metadataBuilder_.clear();
      }
      status_ = 0;

      if (objectsBuilder_ == null) {
        objects_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
      } else {
        objectsBuilder_.clear();
      }
      if (generatedBuilder_ == null) {
        generated_ = null;
      } else {
        generated_ = null;
        generatedBuilder_ = null;
      }
      if (createdBuilder_ == null) {
        created_ = null;
      } else {
        created_ = null;
        createdBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectModels.internal_static_api_models_v1_ObjectGroup_descriptor;
    }

    @java.lang.Override
    public com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup getDefaultInstanceForType() {
      return com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup build() {
      com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup buildPartial() {
      com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup result = new com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.name_ = name_;
      result.description_ = description_;
      result.datasetId_ = datasetId_;
      result.projectId_ = projectId_;
      if (labelsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          labels_ = java.util.Collections.unmodifiableList(labels_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.labels_ = labels_;
      } else {
        result.labels_ = labelsBuilder_.build();
      }
      if (metadataBuilder_ == null) {
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          metadata_ = java.util.Collections.unmodifiableList(metadata_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.metadata_ = metadata_;
      } else {
        result.metadata_ = metadataBuilder_.build();
      }
      result.status_ = status_;
      if (objectsBuilder_ == null) {
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          objects_ = java.util.Collections.unmodifiableList(objects_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.objects_ = objects_;
      } else {
        result.objects_ = objectsBuilder_.build();
      }
      if (generatedBuilder_ == null) {
        result.generated_ = generated_;
      } else {
        result.generated_ = generatedBuilder_.build();
      }
      if (createdBuilder_ == null) {
        result.created_ = created_;
      } else {
        result.created_ = createdBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup) {
        return mergeFrom((com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup other) {
      if (other == com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.getDatasetId().isEmpty()) {
        datasetId_ = other.datasetId_;
        onChanged();
      }
      if (!other.getProjectId().isEmpty()) {
        projectId_ = other.projectId_;
        onChanged();
      }
      if (labelsBuilder_ == null) {
        if (!other.labels_.isEmpty()) {
          if (labels_.isEmpty()) {
            labels_ = other.labels_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureLabelsIsMutable();
            labels_.addAll(other.labels_);
          }
          onChanged();
        }
      } else {
        if (!other.labels_.isEmpty()) {
          if (labelsBuilder_.isEmpty()) {
            labelsBuilder_.dispose();
            labelsBuilder_ = null;
            labels_ = other.labels_;
            bitField0_ = (bitField0_ & ~0x00000020);
            labelsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLabelsFieldBuilder() : null;
          } else {
            labelsBuilder_.addAllMessages(other.labels_);
          }
        }
      }
      if (metadataBuilder_ == null) {
        if (!other.metadata_.isEmpty()) {
          if (metadata_.isEmpty()) {
            metadata_ = other.metadata_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureMetadataIsMutable();
            metadata_.addAll(other.metadata_);
          }
          onChanged();
        }
      } else {
        if (!other.metadata_.isEmpty()) {
          if (metadataBuilder_.isEmpty()) {
            metadataBuilder_.dispose();
            metadataBuilder_ = null;
            metadata_ = other.metadata_;
            bitField0_ = (bitField0_ & ~0x00000040);
            metadataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMetadataFieldBuilder() : null;
          } else {
            metadataBuilder_.addAllMessages(other.metadata_);
          }
        }
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (objectsBuilder_ == null) {
        if (!other.objects_.isEmpty()) {
          if (objects_.isEmpty()) {
            objects_ = other.objects_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureObjectsIsMutable();
            objects_.addAll(other.objects_);
          }
          onChanged();
        }
      } else {
        if (!other.objects_.isEmpty()) {
          if (objectsBuilder_.isEmpty()) {
            objectsBuilder_.dispose();
            objectsBuilder_ = null;
            objects_ = other.objects_;
            bitField0_ = (bitField0_ & ~0x00000100);
            objectsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getObjectsFieldBuilder() : null;
          } else {
            objectsBuilder_.addAllMessages(other.objects_);
          }
        }
      }
      if (other.hasGenerated()) {
        mergeGenerated(other.getGenerated());
      }
      if (other.hasCreated()) {
        mergeCreated(other.getCreated());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1[json_name = "id"];</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1[json_name = "id"];</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1[json_name = "id"];</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1[json_name = "id"];</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1[json_name = "id"];</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2[json_name = "name"];</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2[json_name = "name"];</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2[json_name = "name"];</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2[json_name = "name"];</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2[json_name = "name"];</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 3[json_name = "description"];</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 3[json_name = "description"];</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 3[json_name = "description"];</code>
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3[json_name = "description"];</code>
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3[json_name = "description"];</code>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object datasetId_ = "";
    /**
     * <code>string dataset_id = 4[json_name = "datasetId"];</code>
     */
    public java.lang.String getDatasetId() {
      java.lang.Object ref = datasetId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        datasetId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dataset_id = 4[json_name = "datasetId"];</code>
     */
    public com.google.protobuf.ByteString
        getDatasetIdBytes() {
      java.lang.Object ref = datasetId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        datasetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dataset_id = 4[json_name = "datasetId"];</code>
     */
    public Builder setDatasetId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      datasetId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dataset_id = 4[json_name = "datasetId"];</code>
     */
    public Builder clearDatasetId() {
      
      datasetId_ = getDefaultInstance().getDatasetId();
      onChanged();
      return this;
    }
    /**
     * <code>string dataset_id = 4[json_name = "datasetId"];</code>
     */
    public Builder setDatasetIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      datasetId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object projectId_ = "";
    /**
     * <code>string project_id = 5[json_name = "projectId"];</code>
     */
    public java.lang.String getProjectId() {
      java.lang.Object ref = projectId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        projectId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string project_id = 5[json_name = "projectId"];</code>
     */
    public com.google.protobuf.ByteString
        getProjectIdBytes() {
      java.lang.Object ref = projectId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string project_id = 5[json_name = "projectId"];</code>
     */
    public Builder setProjectId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      projectId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string project_id = 5[json_name = "projectId"];</code>
     */
    public Builder clearProjectId() {
      
      projectId_ = getDefaultInstance().getProjectId();
      onChanged();
      return this;
    }
    /**
     * <code>string project_id = 5[json_name = "projectId"];</code>
     */
    public Builder setProjectIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      projectId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.github.ScienceObjectsDB.java_api.api.models.v1.Label> labels_ =
      java.util.Collections.emptyList();
    private void ensureLabelsIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        labels_ = new java.util.ArrayList<com.github.ScienceObjectsDB.java_api.api.models.v1.Label>(labels_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.ScienceObjectsDB.java_api.api.models.v1.Label, com.github.ScienceObjectsDB.java_api.api.models.v1.Label.Builder, com.github.ScienceObjectsDB.java_api.api.models.v1.LabelOrBuilder> labelsBuilder_;

    /**
     * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
     */
    public java.util.List<com.github.ScienceObjectsDB.java_api.api.models.v1.Label> getLabelsList() {
      if (labelsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(labels_);
      } else {
        return labelsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
     */
    public int getLabelsCount() {
      if (labelsBuilder_ == null) {
        return labels_.size();
      } else {
        return labelsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
     */
    public com.github.ScienceObjectsDB.java_api.api.models.v1.Label getLabels(int index) {
      if (labelsBuilder_ == null) {
        return labels_.get(index);
      } else {
        return labelsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
     */
    public Builder setLabels(
        int index, com.github.ScienceObjectsDB.java_api.api.models.v1.Label value) {
      if (labelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLabelsIsMutable();
        labels_.set(index, value);
        onChanged();
      } else {
        labelsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
     */
    public Builder setLabels(
        int index, com.github.ScienceObjectsDB.java_api.api.models.v1.Label.Builder builderForValue) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        labels_.set(index, builderForValue.build());
        onChanged();
      } else {
        labelsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
     */
    public Builder addLabels(com.github.ScienceObjectsDB.java_api.api.models.v1.Label value) {
      if (labelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLabelsIsMutable();
        labels_.add(value);
        onChanged();
      } else {
        labelsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
     */
    public Builder addLabels(
        int index, com.github.ScienceObjectsDB.java_api.api.models.v1.Label value) {
      if (labelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLabelsIsMutable();
        labels_.add(index, value);
        onChanged();
      } else {
        labelsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
     */
    public Builder addLabels(
        com.github.ScienceObjectsDB.java_api.api.models.v1.Label.Builder builderForValue) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        labels_.add(builderForValue.build());
        onChanged();
      } else {
        labelsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
     */
    public Builder addLabels(
        int index, com.github.ScienceObjectsDB.java_api.api.models.v1.Label.Builder builderForValue) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        labels_.add(index, builderForValue.build());
        onChanged();
      } else {
        labelsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
     */
    public Builder addAllLabels(
        java.lang.Iterable<? extends com.github.ScienceObjectsDB.java_api.api.models.v1.Label> values) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, labels_);
        onChanged();
      } else {
        labelsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
     */
    public Builder clearLabels() {
      if (labelsBuilder_ == null) {
        labels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        labelsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
     */
    public Builder removeLabels(int index) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        labels_.remove(index);
        onChanged();
      } else {
        labelsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
     */
    public com.github.ScienceObjectsDB.java_api.api.models.v1.Label.Builder getLabelsBuilder(
        int index) {
      return getLabelsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
     */
    public com.github.ScienceObjectsDB.java_api.api.models.v1.LabelOrBuilder getLabelsOrBuilder(
        int index) {
      if (labelsBuilder_ == null) {
        return labels_.get(index);  } else {
        return labelsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
     */
    public java.util.List<? extends com.github.ScienceObjectsDB.java_api.api.models.v1.LabelOrBuilder> 
         getLabelsOrBuilderList() {
      if (labelsBuilder_ != null) {
        return labelsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(labels_);
      }
    }
    /**
     * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
     */
    public com.github.ScienceObjectsDB.java_api.api.models.v1.Label.Builder addLabelsBuilder() {
      return getLabelsFieldBuilder().addBuilder(
          com.github.ScienceObjectsDB.java_api.api.models.v1.Label.getDefaultInstance());
    }
    /**
     * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
     */
    public com.github.ScienceObjectsDB.java_api.api.models.v1.Label.Builder addLabelsBuilder(
        int index) {
      return getLabelsFieldBuilder().addBuilder(
          index, com.github.ScienceObjectsDB.java_api.api.models.v1.Label.getDefaultInstance());
    }
    /**
     * <code>repeated .api.models.v1.Label labels = 6[json_name = "labels"];</code>
     */
    public java.util.List<com.github.ScienceObjectsDB.java_api.api.models.v1.Label.Builder> 
         getLabelsBuilderList() {
      return getLabelsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.ScienceObjectsDB.java_api.api.models.v1.Label, com.github.ScienceObjectsDB.java_api.api.models.v1.Label.Builder, com.github.ScienceObjectsDB.java_api.api.models.v1.LabelOrBuilder> 
        getLabelsFieldBuilder() {
      if (labelsBuilder_ == null) {
        labelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.ScienceObjectsDB.java_api.api.models.v1.Label, com.github.ScienceObjectsDB.java_api.api.models.v1.Label.Builder, com.github.ScienceObjectsDB.java_api.api.models.v1.LabelOrBuilder>(
                labels_,
                ((bitField0_ & 0x00000020) == 0x00000020),
                getParentForChildren(),
                isClean());
        labels_ = null;
      }
      return labelsBuilder_;
    }

    private java.util.List<com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata> metadata_ =
      java.util.Collections.emptyList();
    private void ensureMetadataIsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        metadata_ = new java.util.ArrayList<com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata>(metadata_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata, com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata.Builder, com.github.ScienceObjectsDB.java_api.api.models.v1.MetadataOrBuilder> metadataBuilder_;

    /**
     * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
     */
    public java.util.List<com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata> getMetadataList() {
      if (metadataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(metadata_);
      } else {
        return metadataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
     */
    public int getMetadataCount() {
      if (metadataBuilder_ == null) {
        return metadata_.size();
      } else {
        return metadataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
     */
    public com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata getMetadata(int index) {
      if (metadataBuilder_ == null) {
        return metadata_.get(index);
      } else {
        return metadataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
     */
    public Builder setMetadata(
        int index, com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetadataIsMutable();
        metadata_.set(index, value);
        onChanged();
      } else {
        metadataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
     */
    public Builder setMetadata(
        int index, com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        ensureMetadataIsMutable();
        metadata_.set(index, builderForValue.build());
        onChanged();
      } else {
        metadataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
     */
    public Builder addMetadata(com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetadataIsMutable();
        metadata_.add(value);
        onChanged();
      } else {
        metadataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
     */
    public Builder addMetadata(
        int index, com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetadataIsMutable();
        metadata_.add(index, value);
        onChanged();
      } else {
        metadataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
     */
    public Builder addMetadata(
        com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        ensureMetadataIsMutable();
        metadata_.add(builderForValue.build());
        onChanged();
      } else {
        metadataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
     */
    public Builder addMetadata(
        int index, com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        ensureMetadataIsMutable();
        metadata_.add(index, builderForValue.build());
        onChanged();
      } else {
        metadataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
     */
    public Builder addAllMetadata(
        java.lang.Iterable<? extends com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata> values) {
      if (metadataBuilder_ == null) {
        ensureMetadataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, metadata_);
        onChanged();
      } else {
        metadataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
     */
    public Builder clearMetadata() {
      if (metadataBuilder_ == null) {
        metadata_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        metadataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
     */
    public Builder removeMetadata(int index) {
      if (metadataBuilder_ == null) {
        ensureMetadataIsMutable();
        metadata_.remove(index);
        onChanged();
      } else {
        metadataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
     */
    public com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata.Builder getMetadataBuilder(
        int index) {
      return getMetadataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
     */
    public com.github.ScienceObjectsDB.java_api.api.models.v1.MetadataOrBuilder getMetadataOrBuilder(
        int index) {
      if (metadataBuilder_ == null) {
        return metadata_.get(index);  } else {
        return metadataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
     */
    public java.util.List<? extends com.github.ScienceObjectsDB.java_api.api.models.v1.MetadataOrBuilder> 
         getMetadataOrBuilderList() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(metadata_);
      }
    }
    /**
     * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
     */
    public com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata.Builder addMetadataBuilder() {
      return getMetadataFieldBuilder().addBuilder(
          com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata.getDefaultInstance());
    }
    /**
     * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
     */
    public com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata.Builder addMetadataBuilder(
        int index) {
      return getMetadataFieldBuilder().addBuilder(
          index, com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata.getDefaultInstance());
    }
    /**
     * <code>repeated .api.models.v1.Metadata metadata = 7[json_name = "metadata"];</code>
     */
    public java.util.List<com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata.Builder> 
         getMetadataBuilderList() {
      return getMetadataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata, com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata.Builder, com.github.ScienceObjectsDB.java_api.api.models.v1.MetadataOrBuilder> 
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata, com.github.ScienceObjectsDB.java_api.api.models.v1.Metadata.Builder, com.github.ScienceObjectsDB.java_api.api.models.v1.MetadataOrBuilder>(
                metadata_,
                ((bitField0_ & 0x00000040) == 0x00000040),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }

    private int status_ = 0;
    /**
     * <code>.api.models.v1.Status status = 8[json_name = "status"];</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.api.models.v1.Status status = 8[json_name = "status"];</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.api.models.v1.Status status = 8[json_name = "status"];</code>
     */
    public com.github.ScienceObjectsDB.java_api.api.models.v1.Status getStatus() {
      @SuppressWarnings("deprecation")
      com.github.ScienceObjectsDB.java_api.api.models.v1.Status result = com.github.ScienceObjectsDB.java_api.api.models.v1.Status.valueOf(status_);
      return result == null ? com.github.ScienceObjectsDB.java_api.api.models.v1.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.api.models.v1.Status status = 8[json_name = "status"];</code>
     */
    public Builder setStatus(com.github.ScienceObjectsDB.java_api.api.models.v1.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.api.models.v1.Status status = 8[json_name = "status"];</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.github.ScienceObjectsDB.java_api.api.models.v1.Object> objects_ =
      java.util.Collections.emptyList();
    private void ensureObjectsIsMutable() {
      if (!((bitField0_ & 0x00000100) == 0x00000100)) {
        objects_ = new java.util.ArrayList<com.github.ScienceObjectsDB.java_api.api.models.v1.Object>(objects_);
        bitField0_ |= 0x00000100;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.ScienceObjectsDB.java_api.api.models.v1.Object, com.github.ScienceObjectsDB.java_api.api.models.v1.Object.Builder, com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectOrBuilder> objectsBuilder_;

    /**
     * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
     */
    public java.util.List<com.github.ScienceObjectsDB.java_api.api.models.v1.Object> getObjectsList() {
      if (objectsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(objects_);
      } else {
        return objectsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
     */
    public int getObjectsCount() {
      if (objectsBuilder_ == null) {
        return objects_.size();
      } else {
        return objectsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
     */
    public com.github.ScienceObjectsDB.java_api.api.models.v1.Object getObjects(int index) {
      if (objectsBuilder_ == null) {
        return objects_.get(index);
      } else {
        return objectsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
     */
    public Builder setObjects(
        int index, com.github.ScienceObjectsDB.java_api.api.models.v1.Object value) {
      if (objectsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureObjectsIsMutable();
        objects_.set(index, value);
        onChanged();
      } else {
        objectsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
     */
    public Builder setObjects(
        int index, com.github.ScienceObjectsDB.java_api.api.models.v1.Object.Builder builderForValue) {
      if (objectsBuilder_ == null) {
        ensureObjectsIsMutable();
        objects_.set(index, builderForValue.build());
        onChanged();
      } else {
        objectsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
     */
    public Builder addObjects(com.github.ScienceObjectsDB.java_api.api.models.v1.Object value) {
      if (objectsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureObjectsIsMutable();
        objects_.add(value);
        onChanged();
      } else {
        objectsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
     */
    public Builder addObjects(
        int index, com.github.ScienceObjectsDB.java_api.api.models.v1.Object value) {
      if (objectsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureObjectsIsMutable();
        objects_.add(index, value);
        onChanged();
      } else {
        objectsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
     */
    public Builder addObjects(
        com.github.ScienceObjectsDB.java_api.api.models.v1.Object.Builder builderForValue) {
      if (objectsBuilder_ == null) {
        ensureObjectsIsMutable();
        objects_.add(builderForValue.build());
        onChanged();
      } else {
        objectsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
     */
    public Builder addObjects(
        int index, com.github.ScienceObjectsDB.java_api.api.models.v1.Object.Builder builderForValue) {
      if (objectsBuilder_ == null) {
        ensureObjectsIsMutable();
        objects_.add(index, builderForValue.build());
        onChanged();
      } else {
        objectsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
     */
    public Builder addAllObjects(
        java.lang.Iterable<? extends com.github.ScienceObjectsDB.java_api.api.models.v1.Object> values) {
      if (objectsBuilder_ == null) {
        ensureObjectsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, objects_);
        onChanged();
      } else {
        objectsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
     */
    public Builder clearObjects() {
      if (objectsBuilder_ == null) {
        objects_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
      } else {
        objectsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
     */
    public Builder removeObjects(int index) {
      if (objectsBuilder_ == null) {
        ensureObjectsIsMutable();
        objects_.remove(index);
        onChanged();
      } else {
        objectsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
     */
    public com.github.ScienceObjectsDB.java_api.api.models.v1.Object.Builder getObjectsBuilder(
        int index) {
      return getObjectsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
     */
    public com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectOrBuilder getObjectsOrBuilder(
        int index) {
      if (objectsBuilder_ == null) {
        return objects_.get(index);  } else {
        return objectsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
     */
    public java.util.List<? extends com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectOrBuilder> 
         getObjectsOrBuilderList() {
      if (objectsBuilder_ != null) {
        return objectsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(objects_);
      }
    }
    /**
     * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
     */
    public com.github.ScienceObjectsDB.java_api.api.models.v1.Object.Builder addObjectsBuilder() {
      return getObjectsFieldBuilder().addBuilder(
          com.github.ScienceObjectsDB.java_api.api.models.v1.Object.getDefaultInstance());
    }
    /**
     * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
     */
    public com.github.ScienceObjectsDB.java_api.api.models.v1.Object.Builder addObjectsBuilder(
        int index) {
      return getObjectsFieldBuilder().addBuilder(
          index, com.github.ScienceObjectsDB.java_api.api.models.v1.Object.getDefaultInstance());
    }
    /**
     * <code>repeated .api.models.v1.Object objects = 9[json_name = "objects"];</code>
     */
    public java.util.List<com.github.ScienceObjectsDB.java_api.api.models.v1.Object.Builder> 
         getObjectsBuilderList() {
      return getObjectsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.ScienceObjectsDB.java_api.api.models.v1.Object, com.github.ScienceObjectsDB.java_api.api.models.v1.Object.Builder, com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectOrBuilder> 
        getObjectsFieldBuilder() {
      if (objectsBuilder_ == null) {
        objectsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.ScienceObjectsDB.java_api.api.models.v1.Object, com.github.ScienceObjectsDB.java_api.api.models.v1.Object.Builder, com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectOrBuilder>(
                objects_,
                ((bitField0_ & 0x00000100) == 0x00000100),
                getParentForChildren(),
                isClean());
        objects_ = null;
      }
      return objectsBuilder_;
    }

    private com.google.protobuf.Timestamp generated_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> generatedBuilder_;
    /**
     * <code>.google.protobuf.Timestamp generated = 10[json_name = "generated"];</code>
     */
    public boolean hasGenerated() {
      return generatedBuilder_ != null || generated_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp generated = 10[json_name = "generated"];</code>
     */
    public com.google.protobuf.Timestamp getGenerated() {
      if (generatedBuilder_ == null) {
        return generated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : generated_;
      } else {
        return generatedBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp generated = 10[json_name = "generated"];</code>
     */
    public Builder setGenerated(com.google.protobuf.Timestamp value) {
      if (generatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        generated_ = value;
        onChanged();
      } else {
        generatedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp generated = 10[json_name = "generated"];</code>
     */
    public Builder setGenerated(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (generatedBuilder_ == null) {
        generated_ = builderForValue.build();
        onChanged();
      } else {
        generatedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp generated = 10[json_name = "generated"];</code>
     */
    public Builder mergeGenerated(com.google.protobuf.Timestamp value) {
      if (generatedBuilder_ == null) {
        if (generated_ != null) {
          generated_ =
            com.google.protobuf.Timestamp.newBuilder(generated_).mergeFrom(value).buildPartial();
        } else {
          generated_ = value;
        }
        onChanged();
      } else {
        generatedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp generated = 10[json_name = "generated"];</code>
     */
    public Builder clearGenerated() {
      if (generatedBuilder_ == null) {
        generated_ = null;
        onChanged();
      } else {
        generated_ = null;
        generatedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp generated = 10[json_name = "generated"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getGeneratedBuilder() {
      
      onChanged();
      return getGeneratedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp generated = 10[json_name = "generated"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getGeneratedOrBuilder() {
      if (generatedBuilder_ != null) {
        return generatedBuilder_.getMessageOrBuilder();
      } else {
        return generated_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : generated_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp generated = 10[json_name = "generated"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getGeneratedFieldBuilder() {
      if (generatedBuilder_ == null) {
        generatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getGenerated(),
                getParentForChildren(),
                isClean());
        generated_ = null;
      }
      return generatedBuilder_;
    }

    private com.google.protobuf.Timestamp created_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdBuilder_;
    /**
     * <code>.google.protobuf.Timestamp created = 11[json_name = "created"];</code>
     */
    public boolean hasCreated() {
      return createdBuilder_ != null || created_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 11[json_name = "created"];</code>
     */
    public com.google.protobuf.Timestamp getCreated() {
      if (createdBuilder_ == null) {
        return created_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : created_;
      } else {
        return createdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created = 11[json_name = "created"];</code>
     */
    public Builder setCreated(com.google.protobuf.Timestamp value) {
      if (createdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        created_ = value;
        onChanged();
      } else {
        createdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 11[json_name = "created"];</code>
     */
    public Builder setCreated(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdBuilder_ == null) {
        created_ = builderForValue.build();
        onChanged();
      } else {
        createdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 11[json_name = "created"];</code>
     */
    public Builder mergeCreated(com.google.protobuf.Timestamp value) {
      if (createdBuilder_ == null) {
        if (created_ != null) {
          created_ =
            com.google.protobuf.Timestamp.newBuilder(created_).mergeFrom(value).buildPartial();
        } else {
          created_ = value;
        }
        onChanged();
      } else {
        createdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 11[json_name = "created"];</code>
     */
    public Builder clearCreated() {
      if (createdBuilder_ == null) {
        created_ = null;
        onChanged();
      } else {
        created_ = null;
        createdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 11[json_name = "created"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedBuilder() {
      
      onChanged();
      return getCreatedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp created = 11[json_name = "created"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder() {
      if (createdBuilder_ != null) {
        return createdBuilder_.getMessageOrBuilder();
      } else {
        return created_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : created_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created = 11[json_name = "created"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedFieldBuilder() {
      if (createdBuilder_ == null) {
        createdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreated(),
                getParentForChildren(),
                isClean());
        created_ = null;
      }
      return createdBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.models.v1.ObjectGroup)
  }

  // @@protoc_insertion_point(class_scope:api.models.v1.ObjectGroup)
  private static final com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup();
  }

  public static com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ObjectGroup>
      PARSER = new com.google.protobuf.AbstractParser<ObjectGroup>() {
    @java.lang.Override
    public ObjectGroup parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ObjectGroup(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ObjectGroup> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ObjectGroup> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.ScienceObjectsDB.java_api.api.models.v1.ObjectGroup getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

